export type CreateCarModelVariantRawInput = {
    name: unknown
    internal_code: unknown
    built_from: unknown
    built_to: unknown
    body_style: unknown
    drag_coefficient: unknown
    doors: unknown
    weight: unknown
    weight_unit: unknown
    max_power: unknown
    max_power_unit: unknown
    max_torque: unknown
    max_torque_unit: unknown
    cylinders: unknown
    engine_configuration: unknown
    displacement: unknown
    displacement_unit: unknown
    air_induction: unknown
    engine_type: unknown
    energy_source: unknown
    energy_source_2: unknown
    consumption: unknown
    consumption_unit: unknown
    consumption_2: unknown
    consumption_2_unit: unknown
    energy_capacity: unknown
    energy_capacity_unit: unknown
    energy_capacity_2: unknown
    energy_capacity_2_unit: unknown
    transmission: unknown
    gears: unknown
    drivetrain: unknown
    sprint_time_0_100_kmh: unknown
    top_speed: unknown
    top_speed_unit: unknown
    total_production: unknown
}
