import {NodeSpecification} from "../NodeSpecification"
import {NodeType} from "../NodeType"

export const CarModelVariantNodeSpecification: NodeSpecification = {
    type: NodeType.CarModelVariant,
    properties: [
        {
            name: 'name',
            datatype: 'string',
            mandatory: true,
            example: 'BMW M3',
        },
        {
            name: 'internal_code',
            datatype: 'string',
            mandatory: false,
            example: 'E46',
        },
        {
            name: 'built_from',
            datatype: 'number',
            mandatory: false,
            example: 2000,
        },
        {
            name: 'built_to',
            datatype: 'number',
            mandatory: false,
            example: 2006,
        },
        {
            name: 'body_style',
            datatype: 'string',
            mandatory: false,
            example: 'coupe',
        },
        {
            name: 'drag_coefficient',
            datatype: 'number',
            mandatory: false,
            example: 0.31,
        },
        {
            name: 'doors',
            datatype: 'number',
            mandatory: false,
            example: 2,
        },
        {
            name: 'weight',
            datatype: 'number',
            mandatory: false,
            example: 1549,
        },
        {
            name: 'weight_unit',
            datatype: 'string',
            mandatory: false,
            example: 'kg',
        },
        {
            name: 'max_power',
            datatype: 'number',
            mandatory: false,
            example: 343,
        },
        {
            name: 'max_power_unit',
            datatype: 'string',
            mandatory: false,
            example: 'PS',
        },
        {
            name: 'max_torque',
            datatype: 'number',
            mandatory: false,
            example: 365,
        },
        {
            name: 'max_torque_unit',
            datatype: 'string',
            mandatory: false,
            example: 'Nm',
        },
        {
            name: 'cylinders',
            datatype: 'number',
            mandatory: false,
            example: 6,
        },
        {
            name: 'engine_configuration',
            datatype: 'string',
            mandatory: false,
            example: 'inline',
        },
        {
            name: 'displacement',
            datatype: 'number',
            mandatory: false,
            example: 3246,
        },
        {
            name: 'displacement_unit',
            datatype: 'string',
            mandatory: false,
            example: 'ccm',
        },
        {
            name: 'air_induction',
            datatype: 'string',
            mandatory: false,
            example: 'naturally aspirated',
        },
        {
            name: 'engine_type',
            datatype: 'string',
            mandatory: false,
            example: 'otto',
        },
        {
            name: 'energy_source',
            datatype: 'string',
            mandatory: false,
            example: 'petrol',
        },
        {
            name: 'energy_source_2',
            datatype: 'string',
            mandatory: false,
            example: null,
        },
        {
            name: 'consumption',
            datatype: 'number',
            mandatory: false,
            example: 11.9,
        },
        {
            name: 'consumption_unit',
            datatype: 'string',
            mandatory: false,
            example: 'l',
        },
        {
            name: 'consumption_2',
            datatype: 'number',
            mandatory: false,
            example: null,
        },
        {
            name: 'consumption_2_unit',
            datatype: 'string',
            mandatory: false,
            example: null,
        },
        {
            name: 'energy_capacity',
            datatype: 'number',
            mandatory: false,
            example: 63,
        },
        {
            name: 'energy_capacity_unit',
            datatype: 'string',
            mandatory: false,
            example: 'l',
        },
        {
            name: 'energy_capacity_2',
            datatype: 'number',
            mandatory: false,
            example: null,
        },
        {
            name: 'energy_capacity_2_unit',
            datatype: 'string',
            mandatory: false,
            example: null,
        },
        {
            name: 'transmission',
            datatype: 'string',
            mandatory: false,
            example: 'sequential',
        },
        {
            name: 'gears',
            datatype: 'number',
            mandatory: false,
            example: 6,
        },
        {
            name: 'drivetrain',
            datatype: 'string',
            mandatory: false,
            example: 'rwd',
        },
        {
            name: 'sprint_time_0_100_kmh',
            datatype: 'number',
            mandatory: false,
            example: 5.2,
        },
        {
            name: 'top_speed',
            datatype: 'number',
            mandatory: false,
            example: 250,
        },
        {
            name: 'top_speed_unit',
            datatype: 'string',
            mandatory: false,
            example: 'km/h',
        },
        {
            name: 'total_production',
            datatype: 'number',
            mandatory: false,
            example: 50000,
        },
    ],
}
