import {NodeSpecification} from "../NodeSpecification"
import {NodeType} from "../NodeType"

export const CarModelVariantNodeSpecification: NodeSpecification = {
    type: NodeType.CarModelVariant,
    properties: [
        {
            name: 'name',
            datatype: 'string',
            mandatory: true,
            example: 'BMW M3',
            scope: 'user',
            validation: ['mandatory', 'string'],
        },
        {
            name: 'internal_code',
            datatype: 'string',
            mandatory: false,
            example: 'E46',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'built_from',
            datatype: 'number',
            mandatory: false,
            example: 2000,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'built_to',
            datatype: 'number',
            mandatory: false,
            example: 2006,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'body_style',
            datatype: 'string',
            mandatory: false,
            example: 'coupe',
            scope: 'user',
            validation: ['bodyStyle'],
        },
        {
            name: 'drag_coefficient',
            datatype: 'number',
            mandatory: false,
            example: 0.31,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'doors',
            datatype: 'number',
            mandatory: false,
            example: 2,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'weight',
            datatype: 'number',
            mandatory: false,
            example: 1549,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'weight_unit',
            datatype: 'string',
            mandatory: false,
            example: 'kg',
            scope: 'user',
            validation: ['weightUnit'],
        },
        {
            name: 'weight_norm',
            datatype: 'string',
            mandatory: false,
            example: 'EG',
            scope: 'user',
            validation: ['weightNorm'],
        },
        {
            name: 'max_power',
            datatype: 'number',
            mandatory: false,
            example: 343,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'max_power_unit',
            datatype: 'string',
            mandatory: false,
            example: 'PS',
            scope: 'user',
            validation: ['powerUnit'],
        },
        {
            name: 'max_power_norm',
            datatype: 'string',
            mandatory: false,
            example: 'DIN',
            scope: 'user',
            validation: ['powerNorm'],
        },
        {
            name: 'max_torque',
            datatype: 'number',
            mandatory: false,
            example: 365,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'max_torque_unit',
            datatype: 'string',
            mandatory: false,
            example: 'Nm',
            scope: 'user',
            validation: ['torqueUnit'],
        },
        {
            name: 'cylinders',
            datatype: 'number',
            mandatory: false,
            example: 6,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'engine_configuration',
            datatype: 'string',
            mandatory: false,
            example: 'inline',
            scope: 'user',
            validation: ['engineConfiguration'],
        },
        {
            name: 'displacement',
            datatype: 'number',
            mandatory: false,
            example: 3246,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'displacement_unit',
            datatype: 'string',
            mandatory: false,
            example: 'ccm',
            scope: 'user',
            validation: ['displacementUnit'],
        },
        {
            name: 'air_induction',
            datatype: 'string',
            mandatory: false,
            example: 'naturally-aspirated',
            scope: 'user',
            validation: ['airInduction'],
        },
        {
            name: 'engine_type',
            datatype: 'string',
            mandatory: false,
            example: 'otto',
            scope: 'user',
            validation: ['engineType'],
        },
        {
            name: 'energy_source',
            datatype: 'string',
            mandatory: false,
            example: 'petrol',
            scope: 'user',
            validation: ['energySource'],
        },
        {
            name: 'energy_source_2',
            datatype: 'string',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['energySource'],
        },
        {
            name: 'consumption',
            datatype: 'number',
            mandatory: false,
            example: 11.9,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'consumption_unit',
            datatype: 'string',
            mandatory: false,
            example: 'L/100 km',
            scope: 'user',
            validation: ['consumptionUnit'],
        },
        {
            name: 'consumption_norm',
            datatype: 'string',
            mandatory: false,
            example: 'NEDC',
            scope: 'user',
            validation: ['consumptionNorm'],
        },
        {
            name: 'consumption_2',
            datatype: 'number',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'consumption_2_unit',
            datatype: 'string',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['consumptionUnit'],
        },
        {
            name: 'consumption_2_norm',
            datatype: 'string',
            mandatory: false,
            example: 'WLTP',
            scope: 'user',
            validation: ['consumptionNorm'],
        },
        {
            name: 'energy_capacity',
            datatype: 'number',
            mandatory: false,
            example: 63,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'energy_capacity_unit',
            datatype: 'string',
            mandatory: false,
            example: 'l',
            scope: 'user',
            validation: ['capacityUnit'],
        },
        {
            name: 'energy_capacity_2',
            datatype: 'number',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'energy_capacity_2_unit',
            datatype: 'string',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['capacityUnit'],
        },
        {
            name: 'transmission',
            datatype: 'string',
            mandatory: false,
            example: 'sequential',
            scope: 'user',
            validation: ['transmission'],
        },
        {
            name: 'gears',
            datatype: 'number',
            mandatory: false,
            example: 6,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'drivetrain',
            datatype: 'string',
            mandatory: false,
            example: 'RWD',
            scope: 'user',
            validation: ['drivetrain'],
        },
        {
            name: 'sprint_time_0_100_kmh',
            datatype: 'number',
            mandatory: false,
            example: 5.2,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'top_speed',
            datatype: 'number',
            mandatory: false,
            example: 250,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'top_speed_unit',
            datatype: 'string',
            mandatory: false,
            example: 'km/h',
            scope: 'user',
            validation: ['speedUnit'],
        },
        {
            name: 'total_production',
            datatype: 'number',
            mandatory: false,
            example: 50000,
            scope: 'user',
            validation: ['number'],
        },
    ],
}
