import {NodeSpecification} from "../NodeSpecification"
import {NodeType} from "../NodeType"

export const MagazineNodeSpecification: NodeSpecification = {
    type: NodeType.Magazine,
    properties: [
        {
            name: 'name',
            datatype: 'string',
            mandatory: true,
            example: 'Top Gear',
            scope: 'user',
            validation: ['mandatory', 'string'],
        },
        {
            name: 'founded',
            datatype: 'number',
            mandatory: false,
            example: 1993,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'defunct',
            datatype: 'number',
            mandatory: false,
            example: null,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'focus',
            datatype: 'string',
            mandatory: false,
            example: 'sports cars',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'publication_frequency',
            datatype: 'string',
            mandatory: false,
            example: 'monthly',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'single_copy_price',
            datatype: 'number',
            mandatory: false,
            example: 5.99,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'single_copy_price_unit',
            datatype: 'string',
            mandatory: false,
            example: 'GBP',
            validation: ['currencyCode'],
        },
        {
            name: 'publication_format',
            datatype: 'string',
            mandatory: false,
            example: 'print',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'circulation',
            datatype: 'number',
            mandatory: false,
            example: 150884,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'circulation_year',
            datatype: 'number',
            mandatory: false,
            example: 2013,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'publisher',
            datatype: 'string',
            mandatory: false,
            example: 'Immediate Media Company',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'issn',
            datatype: 'string',
            mandatory: false,
            example: '1350-9624',
            validation: ['isValidIssn'],
        },
        {
            name: 'country_code',
            datatype: 'string',
            mandatory: false,
            example: 'GB',
            validation: ['countryCode'],
        },
    ],
}
