import {NodeSpecification} from "../NodeSpecification"
import {NodeType} from "../NodeType"

export const TrackLayoutNodeSpecification: NodeSpecification = {
    type: NodeType.TrackLayout,
    properties: [
        {
            name: 'name',
            datatype: 'string',
            mandatory: true,
            example: 'GP Circuit',
            scope: 'user',
            validation: ['mandatory', 'string'],
        },
        {
            name: 'year_from',
            datatype: 'number',
            mandatory: false,
            example: 1967,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'year_to',
            datatype: 'number',
            mandatory: false,
            example: 1999,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'length',
            datatype: 'number',
            mandatory: false,
            example: 5.397,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'length_unit',
            datatype: 'string',
            mandatory: false,
            example: 'km',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'direction',
            datatype: 'string',
            mandatory: false,
            example: 'clockwise',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'elevation_change',
            datatype: 'number',
            mandatory: false,
            example: 73,
            scope: 'user',
            validation: ['number'],
        },
        {
            name: 'elevation_change_unit',
            datatype: 'string',
            mandatory: false,
            example: 'm',
            scope: 'user',
            validation: ['string'],
        },
        {
            name: 'surface',
            datatype: 'string',
            mandatory: false,
            example: 'asphalt',
            scope: 'user',
            validation: ['string'],
        },
    ],
}
