import {NodeSpecification} from "../NodeSpecification"
import {NodeType} from "../NodeType"

export const VideoNodeSpecification: NodeSpecification = {
    type: NodeType.Video,
    properties: [
        {
            name: 'video_provider',
            datatype: 'string',
            mandatory: true,
            example: 'youtube',
            scope: 'user',
            validation: ['mandatory', 'videoProvider'],
        },
        {
            name: 'external_id',
            datatype: 'string',
            mandatory: true,
            example: 'NqsBncRslsg',
            scope: 'user',
            validation: ['mandatory', 'string'],
        },
        {
            name: 'title',
            datatype: 'string',
            mandatory: false,
            example: 'P1 vs F40',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'description',
            datatype: 'string',
            mandatory: false,
            example: 'Drag Race - P1 vs F40',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'creator',
            datatype: 'string',
            mandatory: false,
            example: 'Lovecars',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'license',
            datatype: 'string',
            mandatory: false,
            example: 'youtube',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'tags',
            datatype: 'string',
            mandatory: false,
            example: 'F40, P1',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'source',
            datatype: 'string',
            mandatory: false,
            example: 'https://www.youtube.com/watch?v=NqsBncRslsg',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'duration',
            datatype: 'string',
            mandatory: false,
            example: 'PT7M24S',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'thumbnail_url_l',
            datatype: 'string',
            mandatory: false,
            example: 'https://i.ytimg.com/vi/NqsBncRslsg/maxresdefault.jpg',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'thumbnail_url_m',
            datatype: 'string',
            mandatory: false,
            example: 'https://i.ytimg.com/vi/NqsBncRslsg/sddefault.jpg',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'thumbnail_url_s',
            datatype: 'string',
            mandatory: false,
            example: 'https://i.ytimg.com/vi/NqsBncRslsg/mqdefault.jpg',
            scope: 'system',
            validation: ['string'],
        },
        {
            name: 'thumbnail_url_xs',
            datatype: 'string',
            mandatory: false,
            example: 'https://i.ytimg.com/vi/NqsBncRslsg/default.jpg',
            scope: 'system',
            validation: ['string'],
        },
    ],
}
