apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dev
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/component: server
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
