apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: more-cars-api
          image: localhost/mc-api:dev
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: $(API_DB_SERVICE_SERVICE_HOST)
