apiVersion: v1
kind: Service
metadata:
  name: app-dev-service
  namespace: dev
  labels:
    app: app-dev
spec:
  type: LoadBalancer
  selector:
    app: app-dev
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
