apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      containers:
        - name:
            neo4j
          image: neo4j:5.23.0
          env:
            - name: NEO4J_AUTH
              value: neo4j/123456789
          volumeMounts:
            - mountPath: /data
              name: api-db-volume
      volumes:
        - name: api-db-volume
          persistentVolumeClaim:
            claimName: api-db-pvc
