import {CarModelVariantNode as CarModelVariantNodeInput} from "../../../../db/nodes/car-model-variants/types/CarModelVariantNode"
import {CarModelVariantNode} from "../types/CarModelVariantNode"

export function convertOutputData(data: CarModelVariantNodeInput): CarModelVariantNode {
    return {
        id: data.properties.id,
        name: data.properties.name,
        internal_code: data.properties.internal_code,
        built_from: data.properties.built_from,
        built_to: data.properties.built_to,
        body_style: data.properties.body_style,
        drag_coefficient: data.properties.drag_coefficient,
        doors: data.properties.doors,
        weight: data.properties.weight,
        weight_unit: data.properties.weight_unit,
        max_power: data.properties.max_power,
        max_power_unit: data.properties.max_power_unit,
        max_torque: data.properties.max_torque,
        max_torque_unit: data.properties.max_torque_unit,
        cylinders: data.properties.cylinders,
        engine_configuration: data.properties.engine_configuration,
        displacement: data.properties.displacement,
        displacement_unit: data.properties.displacement_unit,
        air_induction: data.properties.air_induction,
        engine_type: data.properties.engine_type,
        energy_source: data.properties.energy_source,
        energy_source_2: data.properties.energy_source_2,
        consumption: data.properties.consumption,
        consumption_unit: data.properties.consumption_unit,
        consumption_2: data.properties.consumption_2,
        consumption_2_unit: data.properties.consumption_2_unit,
        energy_capacity: data.properties.energy_capacity,
        energy_capacity_unit: data.properties.energy_capacity_unit,
        energy_capacity_2: data.properties.energy_capacity_2,
        energy_capacity_2_unit: data.properties.energy_capacity_2_unit,
        transmission: data.properties.transmission,
        gears: data.properties.gears,
        drivetrain: data.properties.drivetrain,
        sprint_time_0_100_kmh: data.properties.sprint_time_0_100_kmh,
        top_speed: data.properties.top_speed,
        top_speed_unit: data.properties.top_speed_unit,
        total_production: data.properties.total_production,
        created_at: data.properties.created_at,
        updated_at: data.properties.updated_at,
    } as CarModelVariantNode
}
