export const ImageSchema = {
    type: "object",
    properties: {
        node_type: {type: "string"},
        properties: {
            type: "object",
            properties: {
                id: {type: "integer"},
                image_provider: {type: "string"},
                external_id: {type: "string"},
                name: {type: "string"},
                description: {type: ["string", "null"]},
                creator: {type: "string"},
                license: {type: "string"},
                tags: {type: ["string", "null"]},
                source: {type: "string"},
                image_url_original: {type: "string"},
                image_url_xxl: {type: ["string", "null"]},
                image_url_xl: {type: ["string", "null"]},
                image_url_l: {type: ["string", "null"]},
                image_url_m: {type: ["string", "null"]},
                image_url_s: {type: ["string", "null"]},
                image_url_xs: {type: ["string", "null"]},
                created_at: {type: "string"},
                updated_at: {type: "string"},
            },
            required: [
                "id",
                "created_at",
                "updated_at",
                "image_provider",
                "external_id",
                "name",
                "creator",
                "license",
                "source",
                "image_url_original",
            ],
        },
    },
    additionalProperties: false,
}
