apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../jobs/performance-test

namespace: dev

images:
  - name: docker.io/dennisgerike/more-cars-api
    newName: localhost/mc-api
    newTag: dev
