import {RelationshipType} from "../types/RelationshipType"
import {RelationshipTypeNeo4j} from "../types/RelationshipTypeNeo4j"
import {RelationshipTypeNotFoundError} from "../types/RelationshipTypeNotFoundError"

export function mapDbRelationshipTypeToNeo4jRelationshipType(
    relationshipType: RelationshipType,
): RelationshipTypeNeo4j {
    const mapping = new Map<RelationshipType, RelationshipTypeNeo4j>([
        [RelationshipType.CompanyHasBrand, RelationshipTypeNeo4j.CompanyHasBrand],
        [RelationshipType.CompanyHasImage, RelationshipTypeNeo4j.CompanyHasImage],
        [RelationshipType.CompanyHasPrimeImage, RelationshipTypeNeo4j.CompanyHasPrimeImage],
        [RelationshipType.BrandBelongsToCompany, RelationshipTypeNeo4j.BrandBelongsToCompany],
        [RelationshipType.BrandHasCarModel, RelationshipTypeNeo4j.BrandHasCarModel],
        [RelationshipType.BrandHasImage, RelationshipTypeNeo4j.BrandHasImage],
        [RelationshipType.BrandHasPrimeImage, RelationshipTypeNeo4j.BrandHasPrimeImage],
        [RelationshipType.CarModelBelongsToBrand, RelationshipTypeNeo4j.CarModelBelongsToBrand],
        [RelationshipType.CarModelIsSuccessorOf, RelationshipTypeNeo4j.CarModelIsSuccessorOf],
        [RelationshipType.CarModelHasSuccessor, RelationshipTypeNeo4j.CarModelHasSuccessor],
        [RelationshipType.CarModelHasVariant, RelationshipTypeNeo4j.CarModelHasVariant],
        [RelationshipType.CarModelCoveredByMagazineIssue, RelationshipTypeNeo4j.CarModelCoveredByMagazineIssue],
        [RelationshipType.CarModelCoveredByProgrammeEpisode, RelationshipTypeNeo4j.CarModelCoveredByProgrammeEpisode],
        [RelationshipType.CarModelHasImage, RelationshipTypeNeo4j.CarModelHasImage],
        [RelationshipType.CarModelHasPrimeImage, RelationshipTypeNeo4j.CarModelHasPrimeImage],
        [RelationshipType.CarModelVariantIsVariantOf, RelationshipTypeNeo4j.CarModelVariantIsVariantOf],
        [RelationshipType.CarModelVariantAchievedSessionResult, RelationshipTypeNeo4j.CarModelVariantAchievedSessionResult],
        [RelationshipType.CarModelVariantAchievedLapTime, RelationshipTypeNeo4j.CarModelVariantAchievedLapTime],
        [RelationshipType.CarModelVariantIsPresentedInMagazineIssue, RelationshipTypeNeo4j.CarModelVariantIsPresentedInMagazineIssue],
        [RelationshipType.CarModelVariantReviewedByMagazineIssueWithRating, RelationshipTypeNeo4j.CarModelVariantReviewedByMagazineIssueWithRating],
        [RelationshipType.CarModelVariantFeaturedInProgrammeEpisode, RelationshipTypeNeo4j.CarModelVariantFeaturedInProgrammeEpisode],
        [RelationshipType.CarModelVariantIsFeaturedInRacingGame, RelationshipTypeNeo4j.CarModelVariantIsFeaturedInRacingGame],
        [RelationshipType.CarModelVariantPresentedAtMotorShow, RelationshipTypeNeo4j.CarModelVariantPresentedAtMotorShow],
        [RelationshipType.CarModelVariantHasImage, RelationshipTypeNeo4j.CarModelVariantHasImage],
        [RelationshipType.CarModelVariantHasPrimeImage, RelationshipTypeNeo4j.CarModelVariantHasPrimeImage],
        [RelationshipType.RaceTrackHostedRacingEvent, RelationshipTypeNeo4j.RaceTrackHostedRacingEvent],
        [RelationshipType.RaceTrackHasLayout, RelationshipTypeNeo4j.RaceTrackHasLayout],
        [RelationshipType.RaceTrackHasImage, RelationshipTypeNeo4j.RaceTrackHasImage],
        [RelationshipType.RaceTrackHasPrimeImage, RelationshipTypeNeo4j.RaceTrackHasPrimeImage],
        [RelationshipType.TrackLayoutBelongsToRaceTrack, RelationshipTypeNeo4j.TrackLayoutBelongsToRaceTrack],
        [RelationshipType.TrackLayoutWasUsedByRacingEvent, RelationshipTypeNeo4j.TrackLayoutWasUsedByRacingEvent],
        [RelationshipType.TrackLayoutIsFeaturedInRacingGame, RelationshipTypeNeo4j.TrackLayoutIsFeaturedInRacingGame],
        [RelationshipType.TrackLayoutHasLapTime, RelationshipTypeNeo4j.TrackLayoutHasLapTime],
        [RelationshipType.TrackLayoutHasImage, RelationshipTypeNeo4j.TrackLayoutHasImage],
        [RelationshipType.TrackLayoutHasPrimeImage, RelationshipTypeNeo4j.TrackLayoutHasPrimeImage],
        [RelationshipType.RacingSeriesHasRacingEvent, RelationshipTypeNeo4j.RacingSeriesHasRacingEvent],
        [RelationshipType.RacingSeriesHasImage, RelationshipTypeNeo4j.RacingSeriesHasImage],
        [RelationshipType.RacingSeriesHasPrimeImage, RelationshipTypeNeo4j.RacingSeriesHasPrimeImage],
        [RelationshipType.RacingEventBelongsToRacingSeries, RelationshipTypeNeo4j.RacingEventBelongsToRacingSeries],
        [RelationshipType.RacingEventFollowsEvent, RelationshipTypeNeo4j.RacingEventFollowsEvent],
        [RelationshipType.RacingEventIsFollowedByEvent, RelationshipTypeNeo4j.RacingEventIsFollowedByEvent],
        [RelationshipType.RacingEventTookPlaceAtRaceTrack, RelationshipTypeNeo4j.RacingEventTookPlaceAtRaceTrack],
        [RelationshipType.RacingEventUsedTheTrackLayout, RelationshipTypeNeo4j.RacingEventUsedTheTrackLayout],
        [RelationshipType.RacingEventHasRacingSession, RelationshipTypeNeo4j.RacingEventHasRacingSession],
        [RelationshipType.RacingEventCoveredByMagazineIssue, RelationshipTypeNeo4j.RacingEventCoveredByMagazineIssue],
        [RelationshipType.RacingEventHasImage, RelationshipTypeNeo4j.RacingEventHasImage],
        [RelationshipType.RacingEventHasPrimeImage, RelationshipTypeNeo4j.RacingEventHasPrimeImage],
        [RelationshipType.RacingSessionBelongsToRacingEvent, RelationshipTypeNeo4j.RacingSessionBelongsToRacingEvent],
        [RelationshipType.RacingSessionHasSessionResult, RelationshipTypeNeo4j.RacingSessionHasSessionResult],
        [RelationshipType.RacingSessionHasImage, RelationshipTypeNeo4j.RacingSessionHasImage],
        [RelationshipType.RacingSessionHasPrimeImage, RelationshipTypeNeo4j.RacingSessionHasPrimeImage],
        [RelationshipType.SessionResultBelongsToRacingSession, RelationshipTypeNeo4j.SessionResultBelongsToRacingSession],
        [RelationshipType.SessionResultAchievedWithCarModelVariant, RelationshipTypeNeo4j.SessionResultAchievedWithCarModelVariant],
        [RelationshipType.SessionResultHasLapTime, RelationshipTypeNeo4j.SessionResultHasLapTime],
        [RelationshipType.SessionResultHasImage, RelationshipTypeNeo4j.SessionResultHasImage],
        [RelationshipType.SessionResultHasPrimeImage, RelationshipTypeNeo4j.SessionResultHasPrimeImage],
        [RelationshipType.LapTimeBelongsToSessionResult, RelationshipTypeNeo4j.LapTimeBelongsToSessionResult],
        [RelationshipType.LapTimeAchievedOnTrackLayout, RelationshipTypeNeo4j.LapTimeAchievedOnTrackLayout],
        [RelationshipType.LapTimeAchievedWithCarModelVariant, RelationshipTypeNeo4j.LapTimeAchievedWithCarModelVariant],
        [RelationshipType.LapTimeHasImage, RelationshipTypeNeo4j.LapTimeHasImage],
        [RelationshipType.LapTimeHasPrimeImage, RelationshipTypeNeo4j.LapTimeHasPrimeImage],
        [RelationshipType.RacingGameReleasedOnGamingPlatform, RelationshipTypeNeo4j.RacingGameReleasedOnGamingPlatform],
        [RelationshipType.RacingGameFeaturesCarModelVariant, RelationshipTypeNeo4j.RacingGameFeaturesCarModelVariant],
        [RelationshipType.RacingGameFeaturesTrackLayout, RelationshipTypeNeo4j.RacingGameFeaturesTrackLayout],
        [RelationshipType.RacingGameHasImage, RelationshipTypeNeo4j.RacingGameHasImage],
        [RelationshipType.RacingGameHasPrimeImage, RelationshipTypeNeo4j.RacingGameHasPrimeImage],
        [RelationshipType.GamingPlatformFeaturesRacingGame, RelationshipTypeNeo4j.GamingPlatformFeaturesRacingGame],
        [RelationshipType.GamingPlatformHasImage, RelationshipTypeNeo4j.GamingPlatformHasImage],
        [RelationshipType.GamingPlatformHasPrimeImage, RelationshipTypeNeo4j.GamingPlatformHasPrimeImage],
        [RelationshipType.ImageBelongsToNode, RelationshipTypeNeo4j.ImageBelongsToNode],
        [RelationshipType.ImageIsPrimeImageOfNode, RelationshipTypeNeo4j.ImageIsPrimeImageOfNode],
        [RelationshipType.MagazineHasIssue, RelationshipTypeNeo4j.MagazineHasIssue],
        [RelationshipType.MagazineHasImage, RelationshipTypeNeo4j.MagazineHasImage],
        [RelationshipType.MagazineHasPrimeImage, RelationshipTypeNeo4j.MagazineHasPrimeImage],
        [RelationshipType.MagazineIssueBelongsToMagazine, RelationshipTypeNeo4j.MagazineIssueBelongsToMagazine],
        [RelationshipType.MagazineIssueFollowsIssue, RelationshipTypeNeo4j.MagazineIssueFollowsIssue],
        [RelationshipType.MagazineIssueFollowedByIssue, RelationshipTypeNeo4j.MagazineIssueFollowedByIssue],
        [RelationshipType.MagazineIssueCoversCarModel, RelationshipTypeNeo4j.MagazineIssueCoversCarModel],
        [RelationshipType.MagazineIssuePresentsCarModelVariant, RelationshipTypeNeo4j.MagazineIssuePresentsCarModelVariant],
        [RelationshipType.MagazineIssueReviewedCarModelVariantWithRating, RelationshipTypeNeo4j.MagazineIssueReviewedCarModelVariantWithRating],
        [RelationshipType.MagazineIssueCoversRacingEvent, RelationshipTypeNeo4j.MagazineIssueCoversRacingEvent],
        [RelationshipType.MagazineIssueHasImage, RelationshipTypeNeo4j.MagazineIssueHasImage],
        [RelationshipType.MagazineIssueHasPrimeImage, RelationshipTypeNeo4j.MagazineIssueHasPrimeImage],
        [RelationshipType.RatingByMagazineIssue, RelationshipTypeNeo4j.RatingByMagazineIssue],
        [RelationshipType.RatingForCarModelVariant, RelationshipTypeNeo4j.RatingForCarModelVariant],
        [RelationshipType.RatingHasImage, RelationshipTypeNeo4j.RatingHasImage],
        [RelationshipType.RatingHasPrimeImage, RelationshipTypeNeo4j.RatingHasPrimeImage],
        [RelationshipType.ProgrammeHasEpisode, RelationshipTypeNeo4j.ProgrammeHasEpisode],
        [RelationshipType.ProgrammeHasImage, RelationshipTypeNeo4j.ProgrammeHasImage],
        [RelationshipType.ProgrammeHasPrimeImage, RelationshipTypeNeo4j.ProgrammeHasPrimeImage],
        [RelationshipType.ProgrammeEpisodeBelongsToProgramme, RelationshipTypeNeo4j.ProgrammeEpisodeBelongsToProgramme],
        [RelationshipType.ProgrammeEpisodeCoversCarModel, RelationshipTypeNeo4j.ProgrammeEpisodeCoversCarModel],
        [RelationshipType.ProgrammeEpisodeFeaturesCarModelVariant, RelationshipTypeNeo4j.ProgrammeEpisodeFeaturesCarModelVariant],
        [RelationshipType.MotorShowPresentsCarModelVariant, RelationshipTypeNeo4j.MotorShowPresentsCarModelVariant],
        [RelationshipType.MotorShowHasImage, RelationshipTypeNeo4j.MotorShowHasImage],
        [RelationshipType.MotorShowHasPrimeImage, RelationshipTypeNeo4j.MotorShowHasPrimeImage],
        [RelationshipType.NodeHasImage, RelationshipTypeNeo4j.NodeHasImage],
        [RelationshipType.NodeHasPrimeImage, RelationshipTypeNeo4j.NodeHasPrimeImage],
    ])

    const dbRelationshipType = mapping.get(relationshipType)

    if (!dbRelationshipType) {
        throw new RelationshipTypeNotFoundError(relationshipType)
    }

    return dbRelationshipType
}
