import {RelationshipType} from "../types/RelationshipType"
import {RelationshipTypeNeo4j} from "../types/RelationshipTypeNeo4j"
import {RelationshipTypeNotFoundError} from "../types/RelationshipTypeNotFoundError"

export function mapDbRelationshipTypeToNeo4jRelationshipType(
    relationshipType: RelationshipType,
): RelationshipTypeNeo4j {
    const mapping = new Map<RelationshipType, RelationshipTypeNeo4j>([
        [RelationshipType.NodeHasImage, RelationshipTypeNeo4j.NodeHasImage],
        [RelationshipType.NodeHasPrimeImage, RelationshipTypeNeo4j.NodeHasPrimeImage],
        [RelationshipType.CompanyHasBrand, RelationshipTypeNeo4j.CompanyHasBrand],
        [RelationshipType.CompanyHasImage, RelationshipTypeNeo4j.CompanyHasImage],
        [RelationshipType.CompanyHasPrimeImage, RelationshipTypeNeo4j.CompanyHasPrimeImage],
        [RelationshipType.CompanyHasVideo, RelationshipTypeNeo4j.CompanyHasVideo],
        [RelationshipType.CompanyHasMainVideo, RelationshipTypeNeo4j.CompanyHasMainVideo],
        [RelationshipType.BrandBelongsToCompany, RelationshipTypeNeo4j.BrandBelongsToCompany],
        [RelationshipType.BrandHasCarModel, RelationshipTypeNeo4j.BrandHasCarModel],
        [RelationshipType.BrandHasImage, RelationshipTypeNeo4j.BrandHasImage],
        [RelationshipType.BrandHasPrimeImage, RelationshipTypeNeo4j.BrandHasPrimeImage],
        [RelationshipType.BrandHasVideo, RelationshipTypeNeo4j.BrandHasVideo],
        [RelationshipType.BrandHasMainVideo, RelationshipTypeNeo4j.BrandHasMainVideo],
        [RelationshipType.CarModelBelongsToBrand, RelationshipTypeNeo4j.CarModelBelongsToBrand],
        [RelationshipType.CarModelIsSuccessorOf, RelationshipTypeNeo4j.CarModelIsSuccessorOf],
        [RelationshipType.CarModelHasSuccessor, RelationshipTypeNeo4j.CarModelHasSuccessor],
        [RelationshipType.CarModelHasVariant, RelationshipTypeNeo4j.CarModelHasVariant],
        [RelationshipType.CarModelCoveredByMagazineIssue, RelationshipTypeNeo4j.CarModelCoveredByMagazineIssue],
        [RelationshipType.CarModelCoveredByProgrammeEpisode, RelationshipTypeNeo4j.CarModelCoveredByProgrammeEpisode],
        [RelationshipType.CarModelHasImage, RelationshipTypeNeo4j.CarModelHasImage],
        [RelationshipType.CarModelHasPrimeImage, RelationshipTypeNeo4j.CarModelHasPrimeImage],
        [RelationshipType.CarModelHasVideo, RelationshipTypeNeo4j.CarModelHasVideo],
        [RelationshipType.CarModelHasMainVideo, RelationshipTypeNeo4j.CarModelHasMainVideo],
        [RelationshipType.CarModelVariantIsVariantOf, RelationshipTypeNeo4j.CarModelVariantIsVariantOf],
        [RelationshipType.CarModelVariantAchievedSessionResult, RelationshipTypeNeo4j.CarModelVariantAchievedSessionResult],
        [RelationshipType.CarModelVariantAchievedLapTime, RelationshipTypeNeo4j.CarModelVariantAchievedLapTime],
        [RelationshipType.CarModelVariantIsPresentedInMagazineIssue, RelationshipTypeNeo4j.CarModelVariantIsPresentedInMagazineIssue],
        [RelationshipType.CarModelVariantReviewedByMagazineIssueWithRating, RelationshipTypeNeo4j.CarModelVariantReviewedByMagazineIssueWithRating],
        [RelationshipType.CarModelVariantFeaturedInProgrammeEpisode, RelationshipTypeNeo4j.CarModelVariantFeaturedInProgrammeEpisode],
        [RelationshipType.CarModelVariantIsFeaturedInRacingGame, RelationshipTypeNeo4j.CarModelVariantIsFeaturedInRacingGame],
        [RelationshipType.CarModelVariantHasScaleModel, RelationshipTypeNeo4j.CarModelVariantHasScaleModel],
        [RelationshipType.CarModelVariantPresentedAtMotorShow, RelationshipTypeNeo4j.CarModelVariantPresentedAtMotorShow],
        [RelationshipType.CarModelVariantHasPrice, RelationshipTypeNeo4j.CarModelVariantHasPrice],
        [RelationshipType.CarModelVariantHasImage, RelationshipTypeNeo4j.CarModelVariantHasImage],
        [RelationshipType.CarModelVariantHasPrimeImage, RelationshipTypeNeo4j.CarModelVariantHasPrimeImage],
        [RelationshipType.CarModelVariantHasVideo, RelationshipTypeNeo4j.CarModelVariantHasVideo],
        [RelationshipType.CarModelVariantHasMainVideo, RelationshipTypeNeo4j.CarModelVariantHasMainVideo],
        [RelationshipType.PriceForCarModelVariant, RelationshipTypeNeo4j.PriceForCarModelVariant],
        [RelationshipType.PriceHasImage, RelationshipTypeNeo4j.PriceHasImage],
        [RelationshipType.PriceHasPrimeImage, RelationshipTypeNeo4j.PriceHasPrimeImage],
        [RelationshipType.RaceTrackHostedRacingEvent, RelationshipTypeNeo4j.RaceTrackHostedRacingEvent],
        [RelationshipType.RaceTrackHasLayout, RelationshipTypeNeo4j.RaceTrackHasLayout],
        [RelationshipType.RaceTrackHasImage, RelationshipTypeNeo4j.RaceTrackHasImage],
        [RelationshipType.RaceTrackHasPrimeImage, RelationshipTypeNeo4j.RaceTrackHasPrimeImage],
        [RelationshipType.RaceTrackHasVideo, RelationshipTypeNeo4j.RaceTrackHasVideo],
        [RelationshipType.RaceTrackHasMainVideo, RelationshipTypeNeo4j.RaceTrackHasMainVideo],
        [RelationshipType.TrackLayoutBelongsToRaceTrack, RelationshipTypeNeo4j.TrackLayoutBelongsToRaceTrack],
        [RelationshipType.TrackLayoutWasUsedByRacingEvent, RelationshipTypeNeo4j.TrackLayoutWasUsedByRacingEvent],
        [RelationshipType.TrackLayoutIsFeaturedInRacingGame, RelationshipTypeNeo4j.TrackLayoutIsFeaturedInRacingGame],
        [RelationshipType.TrackLayoutHasLapTime, RelationshipTypeNeo4j.TrackLayoutHasLapTime],
        [RelationshipType.TrackLayoutHasImage, RelationshipTypeNeo4j.TrackLayoutHasImage],
        [RelationshipType.TrackLayoutHasPrimeImage, RelationshipTypeNeo4j.TrackLayoutHasPrimeImage],
        [RelationshipType.TrackLayoutHasVideo, RelationshipTypeNeo4j.TrackLayoutHasVideo],
        [RelationshipType.TrackLayoutHasMainVideo, RelationshipTypeNeo4j.TrackLayoutHasMainVideo],
        [RelationshipType.RacingSeriesHasRacingEvent, RelationshipTypeNeo4j.RacingSeriesHasRacingEvent],
        [RelationshipType.RacingSeriesHasImage, RelationshipTypeNeo4j.RacingSeriesHasImage],
        [RelationshipType.RacingSeriesHasPrimeImage, RelationshipTypeNeo4j.RacingSeriesHasPrimeImage],
        [RelationshipType.RacingSeriesHasVideo, RelationshipTypeNeo4j.RacingSeriesHasVideo],
        [RelationshipType.RacingSeriesHasMainVideo, RelationshipTypeNeo4j.RacingSeriesHasMainVideo],
        [RelationshipType.RacingEventBelongsToRacingSeries, RelationshipTypeNeo4j.RacingEventBelongsToRacingSeries],
        [RelationshipType.RacingEventFollowsEvent, RelationshipTypeNeo4j.RacingEventFollowsEvent],
        [RelationshipType.RacingEventIsFollowedByEvent, RelationshipTypeNeo4j.RacingEventIsFollowedByEvent],
        [RelationshipType.RacingEventTookPlaceAtRaceTrack, RelationshipTypeNeo4j.RacingEventTookPlaceAtRaceTrack],
        [RelationshipType.RacingEventUsedTheTrackLayout, RelationshipTypeNeo4j.RacingEventUsedTheTrackLayout],
        [RelationshipType.RacingEventHasRacingSession, RelationshipTypeNeo4j.RacingEventHasRacingSession],
        [RelationshipType.RacingEventCoveredByMagazineIssue, RelationshipTypeNeo4j.RacingEventCoveredByMagazineIssue],
        [RelationshipType.RacingEventHasImage, RelationshipTypeNeo4j.RacingEventHasImage],
        [RelationshipType.RacingEventHasPrimeImage, RelationshipTypeNeo4j.RacingEventHasPrimeImage],
        [RelationshipType.RacingEventHasVideo, RelationshipTypeNeo4j.RacingEventHasVideo],
        [RelationshipType.RacingEventHasMainVideo, RelationshipTypeNeo4j.RacingEventHasMainVideo],
        [RelationshipType.RacingSessionBelongsToRacingEvent, RelationshipTypeNeo4j.RacingSessionBelongsToRacingEvent],
        [RelationshipType.RacingSessionHasSessionResult, RelationshipTypeNeo4j.RacingSessionHasSessionResult],
        [RelationshipType.RacingSessionHasImage, RelationshipTypeNeo4j.RacingSessionHasImage],
        [RelationshipType.RacingSessionHasPrimeImage, RelationshipTypeNeo4j.RacingSessionHasPrimeImage],
        [RelationshipType.RacingSessionHasVideo, RelationshipTypeNeo4j.RacingSessionHasVideo],
        [RelationshipType.RacingSessionHasMainVideo, RelationshipTypeNeo4j.RacingSessionHasMainVideo],
        [RelationshipType.SessionResultBelongsToRacingSession, RelationshipTypeNeo4j.SessionResultBelongsToRacingSession],
        [RelationshipType.SessionResultAchievedWithCarModelVariant, RelationshipTypeNeo4j.SessionResultAchievedWithCarModelVariant],
        [RelationshipType.SessionResultHasLapTime, RelationshipTypeNeo4j.SessionResultHasLapTime],
        [RelationshipType.SessionResultHasImage, RelationshipTypeNeo4j.SessionResultHasImage],
        [RelationshipType.SessionResultHasPrimeImage, RelationshipTypeNeo4j.SessionResultHasPrimeImage],
        [RelationshipType.LapTimeBelongsToSessionResult, RelationshipTypeNeo4j.LapTimeBelongsToSessionResult],
        [RelationshipType.LapTimeAchievedOnTrackLayout, RelationshipTypeNeo4j.LapTimeAchievedOnTrackLayout],
        [RelationshipType.LapTimeAchievedWithCarModelVariant, RelationshipTypeNeo4j.LapTimeAchievedWithCarModelVariant],
        [RelationshipType.LapTimeHasImage, RelationshipTypeNeo4j.LapTimeHasImage],
        [RelationshipType.LapTimeHasPrimeImage, RelationshipTypeNeo4j.LapTimeHasPrimeImage],
        [RelationshipType.LapTimeHasVideo, RelationshipTypeNeo4j.LapTimeHasVideo],
        [RelationshipType.LapTimeHasMainVideo, RelationshipTypeNeo4j.LapTimeHasMainVideo],
        [RelationshipType.RacingGameReleasedOnGamingPlatform, RelationshipTypeNeo4j.RacingGameReleasedOnGamingPlatform],
        [RelationshipType.RacingGameFeaturesCarModelVariant, RelationshipTypeNeo4j.RacingGameFeaturesCarModelVariant],
        [RelationshipType.RacingGameFeaturesTrackLayout, RelationshipTypeNeo4j.RacingGameFeaturesTrackLayout],
        [RelationshipType.RacingGameHasImage, RelationshipTypeNeo4j.RacingGameHasImage],
        [RelationshipType.RacingGameHasPrimeImage, RelationshipTypeNeo4j.RacingGameHasPrimeImage],
        [RelationshipType.RacingGameHasVideo, RelationshipTypeNeo4j.RacingGameHasVideo],
        [RelationshipType.RacingGameHasMainVideo, RelationshipTypeNeo4j.RacingGameHasMainVideo],
        [RelationshipType.GamingPlatformFeaturesRacingGame, RelationshipTypeNeo4j.GamingPlatformFeaturesRacingGame],
        [RelationshipType.GamingPlatformHasImage, RelationshipTypeNeo4j.GamingPlatformHasImage],
        [RelationshipType.GamingPlatformHasPrimeImage, RelationshipTypeNeo4j.GamingPlatformHasPrimeImage],
        [RelationshipType.GamingPlatformHasVideo, RelationshipTypeNeo4j.GamingPlatformHasVideo],
        [RelationshipType.GamingPlatformHasMainVideo, RelationshipTypeNeo4j.GamingPlatformHasMainVideo],
        [RelationshipType.ModelCarIsScaleModelOfCarModelVariant, RelationshipTypeNeo4j.ModelCarIsScaleModelOfCarModelVariant],
        [RelationshipType.ModelCarMadeByModelCarBrand, RelationshipTypeNeo4j.ModelCarMadeByModelCarBrand],
        [RelationshipType.ModelCarHasImage, RelationshipTypeNeo4j.ModelCarHasImage],
        [RelationshipType.ModelCarHasPrimeImage, RelationshipTypeNeo4j.ModelCarHasPrimeImage],
        [RelationshipType.ModelCarBrandCreatedModelCar, RelationshipTypeNeo4j.ModelCarBrandCreatedModelCar],
        [RelationshipType.ModelCarBrandHasImage, RelationshipTypeNeo4j.ModelCarBrandHasImage],
        [RelationshipType.ModelCarBrandHasPrimeImage, RelationshipTypeNeo4j.ModelCarBrandHasPrimeImage],
        [RelationshipType.MagazineHasIssue, RelationshipTypeNeo4j.MagazineHasIssue],
        [RelationshipType.MagazineHasImage, RelationshipTypeNeo4j.MagazineHasImage],
        [RelationshipType.MagazineHasPrimeImage, RelationshipTypeNeo4j.MagazineHasPrimeImage],
        [RelationshipType.MagazineIssueBelongsToMagazine, RelationshipTypeNeo4j.MagazineIssueBelongsToMagazine],
        [RelationshipType.MagazineIssueFollowsIssue, RelationshipTypeNeo4j.MagazineIssueFollowsIssue],
        [RelationshipType.MagazineIssueFollowedByIssue, RelationshipTypeNeo4j.MagazineIssueFollowedByIssue],
        [RelationshipType.MagazineIssueCoversCarModel, RelationshipTypeNeo4j.MagazineIssueCoversCarModel],
        [RelationshipType.MagazineIssuePresentsCarModelVariant, RelationshipTypeNeo4j.MagazineIssuePresentsCarModelVariant],
        [RelationshipType.MagazineIssueReviewedCarModelVariantWithRating, RelationshipTypeNeo4j.MagazineIssueReviewedCarModelVariantWithRating],
        [RelationshipType.MagazineIssueCoversRacingEvent, RelationshipTypeNeo4j.MagazineIssueCoversRacingEvent],
        [RelationshipType.MagazineIssueHasImage, RelationshipTypeNeo4j.MagazineIssueHasImage],
        [RelationshipType.MagazineIssueHasPrimeImage, RelationshipTypeNeo4j.MagazineIssueHasPrimeImage],
        [RelationshipType.RatingByMagazineIssue, RelationshipTypeNeo4j.RatingByMagazineIssue],
        [RelationshipType.RatingForCarModelVariant, RelationshipTypeNeo4j.RatingForCarModelVariant],
        [RelationshipType.RatingHasImage, RelationshipTypeNeo4j.RatingHasImage],
        [RelationshipType.RatingHasPrimeImage, RelationshipTypeNeo4j.RatingHasPrimeImage],
        [RelationshipType.ProgrammeHasEpisode, RelationshipTypeNeo4j.ProgrammeHasEpisode],
        [RelationshipType.ProgrammeHasImage, RelationshipTypeNeo4j.ProgrammeHasImage],
        [RelationshipType.ProgrammeHasPrimeImage, RelationshipTypeNeo4j.ProgrammeHasPrimeImage],
        [RelationshipType.ProgrammeEpisodeBelongsToProgramme, RelationshipTypeNeo4j.ProgrammeEpisodeBelongsToProgramme],
        [RelationshipType.ProgrammeEpisodeFollowsEpisode, RelationshipTypeNeo4j.ProgrammeEpisodeFollowsEpisode],
        [RelationshipType.ProgrammeEpisodeIsFollowedByEpisode, RelationshipTypeNeo4j.ProgrammeEpisodeIsFollowedByEpisode],
        [RelationshipType.ProgrammeEpisodeCoversCarModel, RelationshipTypeNeo4j.ProgrammeEpisodeCoversCarModel],
        [RelationshipType.ProgrammeEpisodeFeaturesCarModelVariant, RelationshipTypeNeo4j.ProgrammeEpisodeFeaturesCarModelVariant],
        [RelationshipType.ProgrammeEpisodeHasImage, RelationshipTypeNeo4j.ProgrammeEpisodeHasImage],
        [RelationshipType.ProgrammeEpisodeHasPrimeImage, RelationshipTypeNeo4j.ProgrammeEpisodeHasPrimeImage],
        [RelationshipType.MotorShowPresentsCarModelVariant, RelationshipTypeNeo4j.MotorShowPresentsCarModelVariant],
        [RelationshipType.MotorShowHasImage, RelationshipTypeNeo4j.MotorShowHasImage],
        [RelationshipType.MotorShowHasPrimeImage, RelationshipTypeNeo4j.MotorShowHasPrimeImage],
        [RelationshipType.VideoBelongsToNode, RelationshipTypeNeo4j.VideoBelongsToNode],
        [RelationshipType.VideoIsMainVideoOfNode, RelationshipTypeNeo4j.VideoIsMainVideoOfNode],
        [RelationshipType.ImageBelongsToNode, RelationshipTypeNeo4j.ImageBelongsToNode],
        [RelationshipType.ImageIsPrimeImageOfNode, RelationshipTypeNeo4j.ImageIsPrimeImageOfNode],
    ])

    const dbRelationshipType = mapping.get(relationshipType)

    if (!dbRelationshipType) {
        throw new RelationshipTypeNotFoundError(relationshipType)
    }

    return dbRelationshipType
}
