{
    getTests(jql: "project = 'MCA' AND testType = 'Cucumber'", limit: 100, start: $start) {
        total
        start
        limit
        results {
            gherkin
            jira(fields: ["key", "summary", "labels", "issuelinks", "created", "updated"])
        }
    }
}
