---
inject: true
to: specification/OpenAPI/more-cars.openapi.json
before: \"<%= h.changeCase.pascal(startNodeType) %>Properties\"
skip_if: \"<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>\"
---
      "<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>": {
        "type": "object",
        "required": [],
        "properties": {
          "relationship_id": {
            "type": "integer",
            "readOnly": true,
            "example": "123456"
          },
          "relationship_name": {
            "type": "string",
            "readOnly": true,
            "example": "<%= h.changeCase.kebab(relationshipName) %>"
          },
          "relationship_partner": {
            "type": "object",
            "properties": {
              "node_type": {
                "type": "string",
                "example": "<%= h.changeCase.kebab(h.inflection.pluralize(endNodeType)) %>"
              },
              "data": {
                "$ref": "#/components/schemas/<%= h.changeCase.pascal(endNodeType) %>"
              }
            }
          },
          "created_at": {
            "type": "string",
            "readOnly": true,
            "description": "Timestamp for when this relationship was created. Generated by the system. Cannot be changed.",
            "format": "date-time",
            "example": "2025-05-14T11:05:07.793Z"
          },
          "updated_at": {
            "type": "string",
            "readOnly": true,
            "description": "Timestamp for when this relationship was last modified. Generated by the system.",
            "format": "date-time",
            "example": "2025-05-14T11:05:07.793Z"
          }
        }
      },
      "<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>Response": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>"
          }
        }
      },