---
inject: true
to: specification/OpenAPI/more-cars.openapi.json
before: \"<%= h.changeCase.pascal(startNodeType) %>\"
skip_if: \"<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>\"
---
      "<%= h.changeCase.pascal(startNodeType) %><%= h.changeCase.pascal(relationshipName) %>": {
        "type": "object",
        "required": [],
        "properties": {
          "<%= h.changeCase.camel(startNodeType) %>_id": {
            "type": "integer",
            "readOnly": true,
            "example": "1234"
          },
          "<%= h.changeCase.camel(endNodeType) %>_id": {
            "type": "integer",
            "readOnly": true,
            "example": "5678"
          },
          "relationship_id": {
            "type": "integer",
            "readOnly": true,
            "example": "12345678"
          },
          "relationship_name": {
            "type": "string",
            "readOnly": true,
            "example": "<%= h.changeCase.kebab(relationshipName) %>"
          },
          "created_at": {
            "type": "string",
            "readOnly": true,
            "description": "Timestamp for when this node was created. Generated by the system. Cannot be changed.",
            "format": "date-time",
            "example": "2025-05-14T11:05:07.793Z"
          },
          "updated_at": {
            "type": "string",
            "readOnly": true,
            "description": "Timestamp for when this node was last modified. Generated by the system.",
            "format": "date-time",
            "example": "2025-05-14T11:05:07.793Z"
          }
        }
      },