apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
