apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: more-cars-api
          image: docker.io/dennisgerike/more-cars-api:0.12.0
          #image: ghcr.io/more-cars/rest-api:0.12.0
          env:
            - name: DB_HOST
              value: $(API_DB_SERVICE_SERVICE_HOST)
            - name: DB_PASSWORD
              value: "123456789"
          resources:
            requests:
              cpu: "50m"
              memory: "210Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
