apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: more-cars-api
          image: dennisgerike/more-cars-api:0.9.0
          env:
            - name: DB_HOST
              value: $(API_DB_SERVICE_SERVICE_HOST)
          resources:
            requests:
              cpu: "50m"
              memory: "210Mi"
            limits:
              cpu: "100m"
              memory: "400Mi"
