apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db-deployment
  namespace: prod
  labels:
    app.kubernetes.io/name: api-db
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      containers:
        - name:
            neo4j
          image: neo4j:5.23.0
          env:
            - name: NEO4J_AUTH
              value: neo4j/123456789
          resources:
            requests:
              cpu: "50m"
              memory: "800Mi"
            limits:
              cpu: "650m"
              memory: "990Mi"
