apiVersion: v1
kind: Service
metadata:
  name: api-db-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: api-db
  ports:
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
