apiVersion: v1
kind: Service
metadata:
  name: openapi-spec-service
  namespace: prod
  labels:
    app.kubernetes.io/name: openapi-spec
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/component: server
spec:
  type: LoadBalancer
  selector:
    app: openapi-spec
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
