apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-spec-deployment
  namespace: prod
  labels:
    app.kubernetes.io/name: openapi-spec
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/component: documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapi-spec
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openapi-spec
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:v5.18.2
          env:
            - name: URL
              value: http://$(API_SERVICE_SERVICE_HOST)
          resources:
            requests:
              cpu: "10m"
              memory: "5Mi"
            limits:
              cpu: "20m"
              memory: "10Mi"
