apiVersion: batch/v1
kind: Job
metadata:
  name: performance-test-job
  namespace: prod
spec:
  template:
    spec:
      initContainers:
        - name: more-cars-api
          image: dennisgerike/more-cars-api:0.7.0
          command: [ 'cp', '-R', '/app/tests/performance', '/tests' ]
          volumeMounts:
            - name: test-cases-volume
              mountPath: /tests
      containers:
        - name: k6
          image: grafana/k6:0.56.0
          command: [ 'k6', 'run', '/tests/performance/get-api-specification.ts' ]
          env:
            - name: API_URL
              value: http://$(API_SERVICE_SERVICE_HOST)
          volumeMounts:
            - name: test-cases-volume
              mountPath: /tests
      volumes:
        - name: test-cases-volume
          emptyDir:
            sizeLimit: 10Mi
      restartPolicy: Never
