export enum ModelNodeType {
    Node = "",
    Company = "company",
    Brand = "brand",
    CarModel = "car_model",
    CarModelVariant = "car_model_variant",
    Price = "price",
    RaceTrack = "race_track",
    TrackLayout = "track_layout",
    RacingSeries = "racing_series",
    RacingEvent = "racing_event",
    RacingSession = "racing_session",
    SessionResult = "session_result",
    LapTime = "lap_time",
    RacingGame = "racing_game",
    GamingPlatform = "gaming_platform",
    ModelCar = "model_car",
    ModelCarBrand = "model_car_brand",
    Magazine = "magazine",
    MagazineIssue = "magazine_issue",
    Rating = "rating",
    Programme = "programme",
    ProgrammeEpisode = "programme_episode",
    MotorShow = "motor_show",
    Video = "video",
    Image = "image",
}
