apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: more-cars-api
          #image: docker.io/dennisgerike/more-cars-api:latest
          image: ghcr.io/more-cars/rest-api:latest
          env:
            - name: API_NAMESPACE
              value: default
            - name: DB_HOST
              value: $(API_DB_SERVICE_HOST)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api.db-credentials
                  key: password
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: api.basic-auth-credentials
                  key: username
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: api.basic-auth-credentials
                  key: password
            - name: FLICKR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api.flickr-credentials
                  key: apikey
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api.youtube-credentials
                  key: apikey
          resources:
            requests:
              cpu: "50m"
              memory: "150Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
