apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      containers:
        - name:
            neo4j
          image: neo4j:2026.04-community
          env:
            - name: NEO4J_AUTH
              value: 'neo4j/123456789'
          volumeMounts:
            - name: api-db
              mountPath: /data
          resources:
            requests:
              cpu: "400m"
              memory: "1500Mi"
      volumes:
        - name: api-db
          persistentVolumeClaim:
            claimName: api-db
