import {NodeTypeLabel} from "../../src/db/NodeTypeLabel";
import {DbRelationship} from "../../src/db/types/DbRelationship";

export function getAllRelationshipTypes() {
    return new Map<NodeTypeLabel, Map<NodeTypeLabel, DbRelationship[]>>(
        [
            [
                NodeTypeLabel.Company, new Map(
                [
                    [
                        NodeTypeLabel.Brand,
                        [
                            DbRelationship.CompanyHasBrand,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.CompanyHasImage,
                            DbRelationship.CompanyHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.Brand, new Map(
                [
                    [
                        NodeTypeLabel.CarModel,
                        [
                            DbRelationship.BrandHasCarModel,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.BrandHasImage,
                            DbRelationship.BrandHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.CarModel, new Map(
                [
                    [
                        NodeTypeLabel.CarModel,
                        [
                            DbRelationship.CarModelHasSuccessor,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.CarModelHasImage,
                            DbRelationship.CarModelHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.RaceTrack, new Map(
                [
                    [
                        NodeTypeLabel.TrackLayout,
                        [
                            DbRelationship.RaceTrackHasLayout,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.RaceTrackHasImage,
                            DbRelationship.RaceTrackHasPrimeImage,
                        ],
                    ],
                ]),
            ],
            [
                NodeTypeLabel.TrackLayout, new Map(
                [
                    [
                        NodeTypeLabel.LapTime,
                        [
                            DbRelationship.TrackLayoutHasLapTime,
                        ],
                    ], [
                    NodeTypeLabel.Image,
                    [
                        DbRelationship.TrackLayoutHasImage,
                        DbRelationship.TrackLayoutHasPrimeImage,
                    ],
                ],
                ])
            ],
            [
                NodeTypeLabel.RacingSeries, new Map(
                [
                    [
                        NodeTypeLabel.RacingEvent,
                        [
                            DbRelationship.RacingSeriesHasRacingEvent,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.RacingSeriesHasImage,
                            DbRelationship.RacingSeriesHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.RacingEvent, new Map(
                [
                    [
                        NodeTypeLabel.RacingEvent,
                        [
                            DbRelationship.RacingEventIsFollowedByEvent,
                        ],
                    ],
                    [
                        NodeTypeLabel.RaceTrack,
                        [
                            DbRelationship.RacingEventTookPlaceAtRaceTrack,
                        ],
                    ],
                    [
                        NodeTypeLabel.TrackLayout,
                        [
                            DbRelationship.RacingEventUsedTheTrackLayout,
                        ],
                    ],
                    [
                        NodeTypeLabel.RacingSession,
                        [
                            DbRelationship.RacingEventHasRacingSession,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.RacingEventHasImage,
                            DbRelationship.RacingEventHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.RacingSession, new Map(
                [
                    [
                        NodeTypeLabel.SessionResult,
                        [
                            DbRelationship.RacingSessionHasSessionResult,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.RacingSessionHasImage,
                            DbRelationship.RacingSessionHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.SessionResult, new Map(
                [
                    [
                        NodeTypeLabel.LapTime,
                        [
                            DbRelationship.SessionResultHasLapTime,
                        ],
                    ],
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.SessionResultHasImage,
                            DbRelationship.SessionResultHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.LapTime, new Map(
                [
                    [
                        NodeTypeLabel.Image,
                        [
                            DbRelationship.LapTimeHasImage,
                            DbRelationship.LapTimeHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                NodeTypeLabel.Image, new Map(
                [])
            ],
        ])
}
