import {Neo4jNodeType} from "../../src/db/types/Neo4jNodeType";
import {RelationshipType} from "../../src/db/types/RelationshipType";

// This considers only the outgoing relationships (has-relationships, not the belongs-to relationships).
export function getAllRelationshipTypes() {
    return new Map<Neo4jNodeType, Map<Neo4jNodeType, RelationshipType[]>>(
        [
            [
                Neo4jNodeType.Company, new Map(
                [
                    [
                        Neo4jNodeType.Brand,
                        [
                            RelationshipType.CompanyHasBrand,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.CompanyHasImage,
                            RelationshipType.CompanyHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.Brand, new Map(
                [
                    [
                        Neo4jNodeType.CarModel,
                        [
                            RelationshipType.BrandHasCarModel,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.BrandHasImage,
                            RelationshipType.BrandHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.CarModel, new Map(
                [
                    [
                        Neo4jNodeType.CarModel,
                        [
                            RelationshipType.CarModelHasSuccessor,
                        ],
                    ],
                    [
                        Neo4jNodeType.CarModelVariant,
                        [
                            RelationshipType.CarModelHasVariant,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.CarModelHasImage,
                            RelationshipType.CarModelHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.CarModelVariant, new Map(
                [
                    [
                        Neo4jNodeType.SessionResult,
                        [
                            RelationshipType.CarModelVariantAchievedSessionResult,
                        ],
                    ],
                    [
                        Neo4jNodeType.LapTime,
                        [
                            RelationshipType.CarModelVariantAchievedLapTime,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.CarModelVariantHasImage,
                            RelationshipType.CarModelVariantHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.RaceTrack, new Map(
                [
                    [
                        Neo4jNodeType.TrackLayout,
                        [
                            RelationshipType.RaceTrackHasLayout,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.RaceTrackHasImage,
                            RelationshipType.RaceTrackHasPrimeImage,
                        ],
                    ],
                ]),
            ],
            [
                Neo4jNodeType.TrackLayout, new Map(
                [
                    [
                        Neo4jNodeType.LapTime,
                        [
                            RelationshipType.TrackLayoutHasLapTime,
                        ],
                    ], [
                    Neo4jNodeType.Image,
                    [
                        RelationshipType.TrackLayoutHasImage,
                        RelationshipType.TrackLayoutHasPrimeImage,
                    ],
                ],
                ])
            ],
            [
                Neo4jNodeType.RacingSeries, new Map(
                [
                    [
                        Neo4jNodeType.RacingEvent,
                        [
                            RelationshipType.RacingSeriesHasRacingEvent,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.RacingSeriesHasImage,
                            RelationshipType.RacingSeriesHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.RacingEvent, new Map(
                [
                    [
                        Neo4jNodeType.RacingEvent,
                        [
                            RelationshipType.RacingEventIsFollowedByEvent,
                        ],
                    ],
                    [
                        Neo4jNodeType.RaceTrack,
                        [
                            RelationshipType.RacingEventTookPlaceAtRaceTrack,
                        ],
                    ],
                    [
                        Neo4jNodeType.TrackLayout,
                        [
                            RelationshipType.RacingEventUsedTheTrackLayout,
                        ],
                    ],
                    [
                        Neo4jNodeType.RacingSession,
                        [
                            RelationshipType.RacingEventHasRacingSession,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.RacingEventHasImage,
                            RelationshipType.RacingEventHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.RacingSession, new Map(
                [
                    [
                        Neo4jNodeType.SessionResult,
                        [
                            RelationshipType.RacingSessionHasSessionResult,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.RacingSessionHasImage,
                            RelationshipType.RacingSessionHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.SessionResult, new Map(
                [
                    [
                        Neo4jNodeType.LapTime,
                        [
                            RelationshipType.SessionResultHasLapTime,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.SessionResultHasImage,
                            RelationshipType.SessionResultHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.LapTime, new Map(
                [
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.LapTimeHasImage,
                            RelationshipType.LapTimeHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.RacingGame, new Map(
                [
                    [
                        Neo4jNodeType.CarModelVariant,
                        [
                            RelationshipType.RacingGameFeaturesCarModelVariant,
                        ],
                    ],
                    [
                        Neo4jNodeType.TrackLayout,
                        [
                            RelationshipType.RacingGameFeaturesTrackLayout,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.RacingGameHasImage,
                            RelationshipType.RacingGameHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.GamingPlatform, new Map(
                [
                    [
                        Neo4jNodeType.RacingGame,
                        [
                            RelationshipType.GamingPlatformFeaturesRacingGame,
                        ],
                    ],
                    [
                        Neo4jNodeType.Image,
                        [
                            RelationshipType.GamingPlatformHasImage,
                            RelationshipType.GamingPlatformHasPrimeImage,
                        ],
                    ],
                ])
            ],
            [
                Neo4jNodeType.Image, new Map([])
            ],
        ])
}
