export enum ControllerNodeType {
    Company = 'companies',
    Brand = 'brands',
    CarModel = 'car-models',
    CarModelVariant = "car-model-variants",
    Price = "prices",
    RaceTrack = 'race-tracks',
    TrackLayout = 'track-layouts',
    RacingSeries = "racing-series",
    RacingEvent = "racing-events",
    RacingSession = "racing-sessions",
    SessionResult = "session-results",
    LapTime = "lap-times",
    RacingGame = "racing-games",
    GamingPlatform = "gaming-platforms",
    ModelCar = "model-cars",
    ModelCarBrand = "model-car-brands",
    Magazine = "magazines",
    MagazineIssue = "magazine-issues",
    Rating = "ratings",
    Programme = "programmes",
    ProgrammeEpisode = "programme-episodes",
    MotorShow = "motor-shows",
    Image = 'images',
}
