export enum ControllerNodeType {
    Company = 'company',
    Brand = 'brand',
    CarModel = 'car model',
    CarModelVariant = "car model variant",
    RaceTrack = 'race track',
    TrackLayout = 'track layout',
    RacingSeries = "racing series",
    RacingEvent = "racing event",
    RacingSession = "racing session",
    SessionResult = "session result",
    LapTime = "lap time",
    RacingGame = "racing game",
    GamingPlatform = "gaming platform",
    Image = 'image',
}
