export enum ControllerNodeType {
    Company = 'companies',
    Brand = 'brands',
    CarModel = 'car-models',
    CarModelVariant = "car-model-variants",
    RaceTrack = 'race-tracks',
    TrackLayout = 'track-layouts',
    RacingSeries = "racing-series",
    RacingEvent = "racing-events",
    RacingSession = "racing-sessions",
    SessionResult = "session-results",
    LapTime = "lap-times",
    RacingGame = "racing-games",
    GamingPlatform = "gaming-platforms",
    Image = 'images',
}
