apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mc1-volume-pvc
  namespace: mc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
