apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mc1-db-deployment
  namespace: mc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-mc1-db
  template:
    metadata:
      labels:
        app: api-mc1-db
    spec:
      initContainers:
        - name: permission-fixer
          image: ubuntu:22.04
          command:
            [ "/bin/bash", "-c", "chown -R root:root /data" ]
          volumeMounts:
            - name: db-mc1-volume
              mountPath: /data
      containers:
        - name:
            neo4j
          image: neo4j:3.5.19
          env:
            - name: NEO4J_CONF
              value: /data/databases/more-cars-production.db
          volumeMounts:
            - name: db-mc1-volume
              mountPath: /data
      volumes:
        - name: db-mc1-volume
          persistentVolumeClaim:
            claimName: db-mc1-volume-pvc
