apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-dev
  name: app-dev-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - image: localhost/mc-api:dev
          imagePullPolicy: Never
          name: mc-api-dev
