apiVersion: v1
kind: Service
metadata:
  name: openapi-dev-service
  namespace: dev
  labels:
    app: openapi-dev
spec:
  type: LoadBalancer
  selector:
    app: openapi-dev
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
