export enum DbNodeType {
    Company = "Company",
    Brand = "Brand",
    CarModel = "CarModel",
    CarModelVariant = "CarModelVariant",
    RaceTrack = "RaceTrack",
    TrackLayout = "TrackLayout",
    RacingSeries = "RacingSeries",
    RacingEvent = "RacingEvent",
    RacingSession = "RacingSession",
    SessionResult = "SessionResult",
    LapTime = "LapTime",
    RacingGame = "RacingGame",
    GamingPlatform = "GamingPlatform",
    Magazine = "Magazine",
    MagazineIssue = "MagazineIssue",
    Image = "Image",
    Node = "",
}
