export enum Neo4jNodeType {
    Company = "Company",
    Brand = "Brand",
    CarModel = "CarModel",
    CarModelVariant = "CarModelVariant",
    RaceTrack = "RaceTrack",
    TrackLayout = "TrackLayout",
    RacingSeries = "RacingSeries",
    RacingEvent = "RacingEvent",
    RacingSession = "RacingSession",
    SessionResult = "SessionResult",
    LapTime = "LapTime",
    RacingGame = "RacingGame",
    GamingPlatform = "GamingPlatform",
    ModelCar = "ModelCar",
    ModelCarBrand = "ModelCarBrand",
    Magazine = "Magazine",
    MagazineIssue = "MagazineIssue",
    Rating = "Rating",
    Programme = "Programme",
    ProgrammeEpisode = "ProgrammeEpisode",
    MotorShow = "MotorShow",
    Image = "Image",
    Node = "",
}
