apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: prod

images:
  - name: docker.io/dennisgerike/more-cars-api
    newTag: 0.13.0
