export enum RelationshipType {
    CompanyHasBrand = 'HAS_BRAND',
    CompanyHasImage = 'HAS_IMAGE',
    CompanyHasPrimeImage = 'HAS_PRIME_IMAGE',
    BrandBelongsToCompany = 'BELONGS_TO_COMPANY',
    BrandHasCarModel = 'HAS_CAR_MODEL',
    BrandHasImage = 'HAS_IMAGE',
    BrandHasPrimeImage = 'HAS_PRIME_IMAGE',
    CarModelBelongsToBrand = 'BELONGS_TO_BRAND',
    CarModelHasSuccessor = 'HAS_SUCCESSOR',
    CarModelIsSuccessorOf = 'IS_SUCCESSOR_OF',
    CarModelHasImage = 'HAS_IMAGE',
    CarModelHasPrimeImage = 'HAS_PRIME_IMAGE',
    RaceTrackHasLayout = 'HAS_LAYOUT',
    RaceTrackHasImage = 'HAS_IMAGE',
    RaceTrackHasPrimeImage = 'HAS_PRIME_IMAGE',
    TrackLayoutBelongsToRaceTrack = 'BELONGS_TO_RACE_TRACK',
    TrackLayoutHasImage = 'HAS_IMAGE',
    TrackLayoutHasPrimeImage = 'HAS_PRIME_IMAGE',
    RacingSeriesHasRacingEvent = 'HAS_RACING_EVENT',
    RacingSeriesHasImage = 'HAS_IMAGE',
    RacingSeriesHasPrimeImage = 'HAS_PRIME_IMAGE',
    RacingEventBelongsToRacingSeries = 'BELONGS_TO_RACING_SERIES',
    RacingEventIsFollowedByEvent = 'IS_FOLLOWED_BY_EVENT',
    RacingEventFollowsEvent = 'FOLLOWS_EVENT',
    RacingEventTookPlaceAtRaceTrack = 'TOOK_PLACE_AT_RACE_TRACK',
    ImageBelongsToNode = 'BELONGS_TO_NODE',
}
