---
inject: true
to: src/specification/open-api/more-cars.openapi.json
before: \"Relationship\"
skip_if: \"<%= h.changeCase.pascal(nodeType) %>\"
---
<% const properties = JSON.parse(props) -%>
<%
    const schemaProperties = {}

    schemaProperties['created_at'] = {
        type: "string",
        readOnly: true,
        description: "Timestamp for when this node was created. Generated by the system. Cannot be changed.",
        format: "date-time",
        example: "2025-05-14T11:05:07.793Z"
    }

    schemaProperties['updated_at'] = {
        type: "string",
        readOnly: true,
        description: "Timestamp for when this node was last modified. Generated by the system.",
        format: "date-time",
        example: "2025-05-14T11:05:07.793Z"
    }

    properties.forEach(prop => {
        schemaProperties[prop.name] = {
            type: prop.datatype,
            description: "",
            example: prop.example,
        }
    })

    const requiredProperties = []
    properties.forEach(prop => {
        if (prop.mandatory) {
            requiredProperties.push(prop.name)
        }
    })
-%>
      "<%= h.changeCase.pascal(nodeType) %>": {
        "type": "object",
        "required": <%- JSON.stringify(requiredProperties, null, 2).split('\n').map(line => '        ' + line).join('\n') %>,
        "properties": <%- JSON.stringify(schemaProperties, null, 2).split('\n').map(line => '        ' + line).join('\n') %>
      },
      "<%= h.changeCase.pascal(nodeType) %>Response": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "",
            "enum": [
              "<%= h.changeCase.kebab(h.inflection.pluralize(nodeType)) %>"
            ],
            "example": "<%= h.changeCase.kebab(h.inflection.pluralize(nodeType)) %>"
          },
          "id": {
            "type": "integer",
            "description": "A unique identifier which is generated by the system.",
            "example": "1234"
          },
          "attributes": {
            "$ref": "#/components/schemas/<%= h.changeCase.pascal(nodeType) %>"
          }
        }
      },
<%
    const enumProperties = []

    enumProperties.push('created_at')
    enumProperties.push('updated_at')

    properties.forEach(prop => {
        enumProperties.push(prop.name)
    })
-%>
      "<%= h.changeCase.pascal(nodeType) %>Properties": {
        "type": "string",
        "enum": <%- JSON.stringify(enumProperties, null, 2).split('\n').map(line => '        ' + line).join('\n') %>,
        "default": "name"
      },