apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openapi-dev
  name: openapi-dev-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapi-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openapi-dev
    spec:
      containers:
        - name: swagger-ui-dev
          image: swaggerapi/swagger-ui
