export enum NodeTypeLabelOld {
    Company = "company",
    Brand = "brand",
    CarModel = "carmodel",
    CarModelVariant = "carmodelvariation",
    RaceTrack = "racetrack",
    TrackLayout = "racetrackvariant",
    RacingSeries = "racingseries",
    RacingEvent = "racingseriesevent",
    RacingSession = "racingeventsession",
    SessionResult = "raceresult",
    LapTime = "laptime",
    RacingGame = "racinggame",
    GamingPlatform = "gamingplatform",
    Magazine = "carmagazine",
    MagazineIssue = "carmagazineissue",
    Rating = "rating",
    Image = "image",
}