apiVersion: batch/v1
kind: Job
metadata:
  name: developer-tests-job
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: more-cars-api
          image: ghcr.io/more-cars/rest-api:latest
          env:
            - name: DB_HOST
              value: $(API_DB_SERVICE_SERVICE_HOST)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          command: [ "/bin/sh", "-c" ]
          args:
            - |

              npm ci

              if [ "$CODE_COVERAGE_ENABLED" = true ]; then
                npx vitest run -c tests/developer/vite.config.ts --coverage --maxWorkers=1 --fileParallelism=false
              else
                npx vitest run -c tests/developer/vite.config.ts --maxWorkers=1 --fileParallelism=false
              fi

              # Vitest will return with exit code 1 should any of the tests fail.
              # That would also fail this job. We don't want that.
              # Evaluating the test results happens outside of this job.
              # We only want to know if the job has finished. Therefore always returning code 0 here.
              exit 0
