import express from "express"
import {CarModelVariantController} from "../../controllers/node-types/CarModelVariantController"

const router = express.Router()

router.post('/car-model-variants', CarModelVariantController.create)
router.get('/car-model-variants/:id', CarModelVariantController.getById)
router.get('/car-model-variants', CarModelVariantController.getAll)
router.delete('/car-model-variants/:id', CarModelVariantController.delete)
router.post('/car-model-variants/:carModelVariantId/is-variant-of/:carModelId', CarModelVariantController.createIsVariantOfRelation)
router.get('/car-model-variants/:carModelVariantId/is-variant-of', CarModelVariantController.getIsVariantOfRelation)
router.delete('/car-model-variants/:carModelVariantId/is-variant-of/:carModelId', CarModelVariantController.deleteIsVariantOfRelation)
router.post('/car-model-variants/:carModelVariantId/achieved-session-result/:sessionResultId', CarModelVariantController.createAchievedSessionResultRelation)
router.get('/car-model-variants/:carModelVariantId/achieved-session-result', CarModelVariantController.getAllAchievedSessionResultRelations)
router.delete('/car-model-variants/:carModelVariantId/achieved-session-result/:sessionResultId', CarModelVariantController.deleteAchievedSessionResultRelation)
router.post('/car-model-variants/:carModelVariantId/achieved-lap-time/:lapTimeId', CarModelVariantController.createAchievedLapTimeRelation)
router.get('/car-model-variants/:carModelVariantId/achieved-lap-time', CarModelVariantController.getAllAchievedLapTimeRelations)
router.delete('/car-model-variants/:carModelVariantId/achieved-lap-time/:lapTimeId', CarModelVariantController.deleteAchievedLapTimeRelation)
router.post('/car-model-variants/:carModelVariantId/is-presented-in-magazine-issue/:magazineIssueId', CarModelVariantController.createIsPresentedInMagazineIssueRelation)
router.get('/car-model-variants/:carModelVariantId/is-presented-in-magazine-issue', CarModelVariantController.getAllIsPresentedInMagazineIssueRelations)
router.delete('/car-model-variants/:carModelVariantId/is-presented-in-magazine-issue/:magazineIssueId', CarModelVariantController.deleteIsPresentedInMagazineIssueRelation)
router.post('/car-model-variants/:carModelVariantId/reviewed-by-magazine-issue-with-rating/:ratingId', CarModelVariantController.createReviewedByMagazineIssueWithRatingRelation)
router.get('/car-model-variants/:carModelVariantId/reviewed-by-magazine-issue-with-rating', CarModelVariantController.getAllReviewedByMagazineIssueWithRatingRelations)
router.delete('/car-model-variants/:carModelVariantId/reviewed-by-magazine-issue-with-rating/:ratingId', CarModelVariantController.deleteReviewedByMagazineIssueWithRatingRelation)
router.post('/car-model-variants/:carModelVariantId/featured-in-programme-episode/:programmeEpisodeId', CarModelVariantController.createFeaturedInProgrammeEpisodeRelation)
router.get('/car-model-variants/:carModelVariantId/featured-in-programme-episode', CarModelVariantController.getAllFeaturedInProgrammeEpisodeRelations)
router.delete('/car-model-variants/:carModelVariantId/featured-in-programme-episode/:programmeEpisodeId', CarModelVariantController.deleteFeaturedInProgrammeEpisodeRelation)
router.post('/car-model-variants/:carModelVariantId/is-featured-in-racing-game/:racingGameId', CarModelVariantController.createIsFeaturedInRacingGameRelation)
router.get('/car-model-variants/:carModelVariantId/is-featured-in-racing-game', CarModelVariantController.getAllIsFeaturedInRacingGameRelations)
router.delete('/car-model-variants/:carModelVariantId/is-featured-in-racing-game/:racingGameId', CarModelVariantController.deleteIsFeaturedInRacingGameRelation)
router.post('/car-model-variants/:carModelVariantId/presented-at-motor-show/:motorShowId', CarModelVariantController.createPresentedAtMotorShowRelation)
router.get('/car-model-variants/:carModelVariantId/presented-at-motor-show', CarModelVariantController.getAllPresentedAtMotorShowRelations)
router.delete('/car-model-variants/:carModelVariantId/presented-at-motor-show/:motorShowId', CarModelVariantController.deletePresentedAtMotorShowRelation)
router.post('/car-model-variants/:carModelVariantId/has-price/:priceId', CarModelVariantController.createHasPriceRelation)
router.post('/car-model-variants/:carModelVariantId/has-image/:imageId', CarModelVariantController.createHasImageRelation)
router.get('/car-model-variants/:carModelVariantId/has-image', CarModelVariantController.getAllHasImageRelations)
router.delete('/car-model-variants/:carModelVariantId/has-image/:imageId', CarModelVariantController.deleteHasImageRelation)
router.post('/car-model-variants/:carModelVariantId/has-prime-image/:imageId', CarModelVariantController.createHasPrimeImageRelation)
router.get('/car-model-variants/:carModelVariantId/has-prime-image', CarModelVariantController.getHasPrimeImageRelation)
router.delete('/car-model-variants/:carModelVariantId/has-prime-image/:imageId', CarModelVariantController.deleteHasPrimeImageRelation)

export default router
