import express from "express"
import {CarModelVariantController} from "../../controllers/node-types/CarModelVariantController"

const router = express.Router()

router.post('/car-model-variants', CarModelVariantController.create)
router.get('/car-model-variants/:id', CarModelVariantController.getById)
router.get('/car-model-variants', CarModelVariantController.getAll)
router.patch('/car-model-variants/:id', CarModelVariantController.update)
router.delete('/car-model-variants/:id', CarModelVariantController.delete)
router.post('/car-model-variants/:carModelVariantId/relationships/is-variant-of', CarModelVariantController.createIsVariantOfRelation)
router.get('/car-model-variants/:carModelVariantId/is-variant-of', CarModelVariantController.getIsVariantOfRelation)
router.delete('/car-model-variants/:carModelVariantId/relationships/is-variant-of', CarModelVariantController.deleteIsVariantOfRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/achieved-session-result', CarModelVariantController.createAchievedSessionResultRelation)
router.get('/car-model-variants/:carModelVariantId/achieved-session-result', CarModelVariantController.getAllAchievedSessionResultRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/achieved-session-result', CarModelVariantController.deleteAchievedSessionResultRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/achieved-lap-time', CarModelVariantController.createAchievedLapTimeRelation)
router.get('/car-model-variants/:carModelVariantId/achieved-lap-time', CarModelVariantController.getAllAchievedLapTimeRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/achieved-lap-time', CarModelVariantController.deleteAchievedLapTimeRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/is-presented-in-magazine-issue', CarModelVariantController.createIsPresentedInMagazineIssueRelation)
router.get('/car-model-variants/:carModelVariantId/is-presented-in-magazine-issue', CarModelVariantController.getAllIsPresentedInMagazineIssueRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/is-presented-in-magazine-issue', CarModelVariantController.deleteIsPresentedInMagazineIssueRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/reviewed-by-magazine-issue-with-rating', CarModelVariantController.createReviewedByMagazineIssueWithRatingRelation)
router.get('/car-model-variants/:carModelVariantId/reviewed-by-magazine-issue-with-rating', CarModelVariantController.getAllReviewedByMagazineIssueWithRatingRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/reviewed-by-magazine-issue-with-rating', CarModelVariantController.deleteReviewedByMagazineIssueWithRatingRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/featured-in-programme-episode', CarModelVariantController.createFeaturedInProgrammeEpisodeRelation)
router.get('/car-model-variants/:carModelVariantId/featured-in-programme-episode', CarModelVariantController.getAllFeaturedInProgrammeEpisodeRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/featured-in-programme-episode', CarModelVariantController.deleteFeaturedInProgrammeEpisodeRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/is-featured-in-racing-game', CarModelVariantController.createIsFeaturedInRacingGameRelation)
router.get('/car-model-variants/:carModelVariantId/is-featured-in-racing-game', CarModelVariantController.getAllIsFeaturedInRacingGameRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/is-featured-in-racing-game', CarModelVariantController.deleteIsFeaturedInRacingGameRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-scale-model', CarModelVariantController.createHasScaleModelRelation)
router.get('/car-model-variants/:carModelVariantId/has-scale-model', CarModelVariantController.getAllHasScaleModelRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-scale-model', CarModelVariantController.deleteHasScaleModelRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/presented-at-motor-show', CarModelVariantController.createPresentedAtMotorShowRelation)
router.get('/car-model-variants/:carModelVariantId/presented-at-motor-show', CarModelVariantController.getAllPresentedAtMotorShowRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/presented-at-motor-show', CarModelVariantController.deletePresentedAtMotorShowRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-price', CarModelVariantController.createHasPriceRelation)
router.get('/car-model-variants/:carModelVariantId/has-price', CarModelVariantController.getAllHasPriceRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-price', CarModelVariantController.deleteHasPriceRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/is-covered-by-book', CarModelVariantController.createIsCoveredByBookRelation)
router.get('/car-model-variants/:carModelVariantId/is-covered-by-book', CarModelVariantController.getAllIsCoveredByBookRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/is-covered-by-book', CarModelVariantController.deleteIsCoveredByBookRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-image', CarModelVariantController.createHasImageRelation)
router.get('/car-model-variants/:carModelVariantId/has-image', CarModelVariantController.getAllHasImageRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-image', CarModelVariantController.deleteHasImageRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-prime-image', CarModelVariantController.createHasPrimeImageRelation)
router.get('/car-model-variants/:carModelVariantId/has-prime-image', CarModelVariantController.getHasPrimeImageRelation)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-prime-image', CarModelVariantController.deleteHasPrimeImageRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-video', CarModelVariantController.createHasVideoRelation)
router.get('/car-model-variants/:carModelVariantId/has-video', CarModelVariantController.getAllHasVideoRelations)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-video', CarModelVariantController.deleteHasVideoRelation)
router.post('/car-model-variants/:carModelVariantId/relationships/has-main-video', CarModelVariantController.createHasMainVideoRelation)
router.get('/car-model-variants/:carModelVariantId/has-main-video', CarModelVariantController.getHasMainVideoRelation)
router.delete('/car-model-variants/:carModelVariantId/relationships/has-main-video', CarModelVariantController.deleteHasMainVideoRelation)

export default router
