import express from "express"
import {CarModelController} from "../../controllers/node-types/CarModelController"

const router = express.Router()

router.post('/car-models', CarModelController.create)
router.get('/car-models/:id', CarModelController.getById)
router.get('/car-models', CarModelController.getAll)
router.patch('/car-models/:id', CarModelController.update)
router.delete('/car-models/:id', CarModelController.delete)
router.post('/car-models/:carModelId/relationships/belongs-to-brand', CarModelController.createBelongsToBrandRelation)
router.get('/car-models/:carModelId/belongs-to-brand', CarModelController.getBelongsToBrandRelation)
router.delete('/car-models/:carModelId/relationships/belongs-to-brand', CarModelController.deleteBelongsToBrandRelation)
router.post('/car-models/:carModelId/relationships/has-successor', CarModelController.createHasSuccessorRelation)
router.get('/car-models/:carModelId/has-successor', CarModelController.getHasSuccessorRelation)
router.delete('/car-models/:carModelId/relationships/has-successor', CarModelController.deleteHasSuccessorRelation)
router.post('/car-models/:carModelId/relationships/is-successor-of', CarModelController.createIsSuccessorOfRelation)
router.get('/car-models/:carModelId/is-successor-of', CarModelController.getIsSuccessorOfRelation)
router.delete('/car-models/:carModelId/relationships/is-successor-of', CarModelController.deleteIsSuccessorOfRelation)
router.post('/car-models/:carModelId/relationships/has-variant', CarModelController.createHasVariantRelation)
router.get('/car-models/:carModelId/has-variant', CarModelController.getAllHasVariantRelations)
router.delete('/car-models/:carModelId/relationships/has-variant', CarModelController.deleteHasVariantRelation)
router.post('/car-models/:carModelId/relationships/covered-by-magazine-issue', CarModelController.createCoveredByMagazineIssueRelation)
router.get('/car-models/:carModelId/covered-by-magazine-issue', CarModelController.getAllCoveredByMagazineIssueRelations)
router.delete('/car-models/:carModelId/relationships/covered-by-magazine-issue', CarModelController.deleteCoveredByMagazineIssueRelation)
router.post('/car-models/:carModelId/relationships/covered-by-programme-episode', CarModelController.createCoveredByProgrammeEpisodeRelation)
router.get('/car-models/:carModelId/covered-by-programme-episode', CarModelController.getAllCoveredByProgrammeEpisodeRelations)
router.delete('/car-models/:carModelId/relationships/covered-by-programme-episode', CarModelController.deleteCoveredByProgrammeEpisodeRelation)
router.post('/car-models/:carModelId/relationships/has-image', CarModelController.createHasImageRelation)
router.get('/car-models/:carModelId/has-image', CarModelController.getAllHasImageRelations)
router.delete('/car-models/:carModelId/relationships/has-image', CarModelController.deleteHasImageRelation)
router.post('/car-models/:carModelId/relationships/has-prime-image', CarModelController.createHasPrimeImageRelation)
router.get('/car-models/:carModelId/has-prime-image', CarModelController.getHasPrimeImageRelation)
router.delete('/car-models/:carModelId/relationships/has-prime-image', CarModelController.deleteHasPrimeImageRelation)
router.post('/car-models/:carModelId/relationships/has-video', CarModelController.createHasVideoRelation)
router.get('/car-models/:carModelId/has-video', CarModelController.getAllHasVideoRelations)
router.delete('/car-models/:carModelId/relationships/has-video', CarModelController.deleteHasVideoRelation)
router.post('/car-models/:carModelId/relationships/has-main-video', CarModelController.createHasMainVideoRelation)
router.get('/car-models/:carModelId/has-main-video', CarModelController.getHasMainVideoRelation)
router.delete('/car-models/:carModelId/relationships/has-main-video', CarModelController.deleteHasMainVideoRelation)

export default router
