import express from "express"
import {CarModelController} from "../../controllers/node-types/CarModelController"

const router = express.Router()

router.post('/car-models', CarModelController.create)
router.get('/car-models/:id', CarModelController.getById)
router.get('/car-models', CarModelController.getAll)
router.delete('/car-models/:id', CarModelController.delete)
router.post('/car-models/:carModelId/belongs-to-brand/:brandId', CarModelController.createBelongsToBrandRelation)
router.get('/car-models/:carModelId/belongs-to-brand', CarModelController.getBelongsToBrandRelation)
router.delete('/car-models/:carModelId/belongs-to-brand/:brandId', CarModelController.deleteBelongsToBrandRelation)
router.post('/car-models/:carModelId/has-successor/:relationPartnerId', CarModelController.createHasSuccessorRelation)
router.get('/car-models/:carModelId/has-successor', CarModelController.getHasSuccessorRelation)
router.delete('/car-models/:carModelId/has-successor/:partnerId', CarModelController.deleteHasSuccessorRelation)
router.post('/car-models/:carModelId/is-successor-of/:partnerId', CarModelController.createIsSuccessorOfRelation)
router.get('/car-models/:carModelId/is-successor-of', CarModelController.getIsSuccessorOfRelation)
router.delete('/car-models/:carModelId/is-successor-of/:partnerId', CarModelController.deleteIsSuccessorOfRelation)
router.post('/car-models/:carModelId/has-variant/:carModelVariantId', CarModelController.createHasVariantRelation)
router.get('/car-models/:carModelId/has-variant', CarModelController.getAllHasVariantRelations)
router.delete('/car-models/:carModelId/has-variant/:carModelVariantId', CarModelController.deleteHasVariantRelation)
router.post('/car-models/:carModelId/covered-by-magazine-issue/:magazineIssueId', CarModelController.createCoveredByMagazineIssueRelation)
router.get('/car-models/:carModelId/covered-by-magazine-issue', CarModelController.getAllCoveredByMagazineIssueRelations)
router.delete('/car-models/:carModelId/covered-by-magazine-issue/:magazineIssueId', CarModelController.deleteCoveredByMagazineIssueRelation)
router.post('/car-models/:carModelId/covered-by-programme-episode/:programmeEpisodeId', CarModelController.createCoveredByProgrammeEpisodeRelation)
router.get('/car-models/:carModelId/covered-by-programme-episode', CarModelController.getAllCoveredByProgrammeEpisodeRelations)
router.delete('/car-models/:carModelId/covered-by-programme-episode/:programmeEpisodeId', CarModelController.deleteCoveredByProgrammeEpisodeRelation)
router.post('/car-models/:carModelId/has-image/:imageId', CarModelController.createHasImageRelation)
router.get('/car-models/:carModelId/has-image', CarModelController.getAllHasImageRelations)
router.delete('/car-models/:carModelId/has-image/:imageId', CarModelController.deleteHasImageRelation)
router.post('/car-models/:carModelId/has-prime-image/:imageId', CarModelController.createHasPrimeImageRelation)
router.get('/car-models/:carModelId/has-prime-image', CarModelController.getHasPrimeImageRelation)
router.delete('/car-models/:carModelId/has-prime-image/:imageId', CarModelController.deleteHasPrimeImageRelation)
router.post('/car-models/:carModelId/has-video/:videoId', CarModelController.createHasVideoRelation)
router.get('/car-models/:carModelId/has-video', CarModelController.getAllHasVideoRelations)
router.delete('/car-models/:carModelId/has-video/:videoId', CarModelController.deleteHasVideoRelation)
router.post('/car-models/:carModelId/has-main-video/:videoId', CarModelController.createHasMainVideoRelation)
router.get('/car-models/:carModelId/has-main-video', CarModelController.getHasMainVideoRelation)
router.delete('/car-models/:carModelId/has-main-video/:videoId', CarModelController.deleteHasMainVideoRelation)

export default router
