import express from "express"
import {LapTimeController} from "../../controllers/node-types/LapTimeController"

const router = express.Router()

router.post('/lap-times', LapTimeController.create)
router.get('/lap-times/:id', LapTimeController.getById)
router.get('/lap-times', LapTimeController.getAll)
router.patch('/lap-times/:id', LapTimeController.update)
router.delete('/lap-times/:id', LapTimeController.delete)
router.post('/lap-times/:lapTimeId/relationships/belongs-to-session-result', LapTimeController.createBelongsToSessionResultRelation)
router.get('/lap-times/:lapTimeId/belongs-to-session-result', LapTimeController.getBelongsToSessionResultRelation)
router.delete('/lap-times/:lapTimeId/relationships/belongs-to-session-result', LapTimeController.deleteBelongsToSessionResultRelation)
router.post('/lap-times/:lapTimeId/relationships/achieved-on-track-layout', LapTimeController.createAchievedOnTrackLayoutRelation)
router.get('/lap-times/:lapTimeId/achieved-on-track-layout', LapTimeController.getAchievedOnTrackLayoutRelation)
router.delete('/lap-times/:lapTimeId/relationships/achieved-on-track-layout', LapTimeController.deleteAchievedOnTrackLayoutRelation)
router.post('/lap-times/:lapTimeId/relationships/achieved-with-car-model-variant', LapTimeController.createAchievedWithCarModelVariantRelation)
router.get('/lap-times/:lapTimeId/achieved-with-car-model-variant', LapTimeController.getAchievedWithCarModelVariantRelation)
router.delete('/lap-times/:lapTimeId/relationships/achieved-with-car-model-variant', LapTimeController.deleteAchievedWithCarModelVariantRelation)
router.post('/lap-times/:lapTimeId/relationships/documented-in-magazine-issue', LapTimeController.createDocumentedInMagazineIssueRelation)
router.get('/lap-times/:lapTimeId/documented-in-magazine-issue', LapTimeController.getDocumentedInMagazineIssueRelation)
router.delete('/lap-times/:lapTimeId/relationships/documented-in-magazine-issue', LapTimeController.deleteDocumentedInMagazineIssueRelation)
router.post('/lap-times/:lapTimeId/relationships/has-image', LapTimeController.createHasImageRelation)
router.get('/lap-times/:lapTimeId/has-image', LapTimeController.getAllHasImageRelations)
router.delete('/lap-times/:lapTimeId/relationships/has-image', LapTimeController.deleteHasImageRelation)
router.post('/lap-times/:lapTimeId/relationships/has-prime-image', LapTimeController.createHasPrimeImageRelation)
router.get('/lap-times/:lapTimeId/has-prime-image', LapTimeController.getHasPrimeImageRelation)
router.delete('/lap-times/:lapTimeId/relationships/has-prime-image', LapTimeController.deleteHasPrimeImageRelation)
router.post('/lap-times/:lapTimeId/relationships/has-video', LapTimeController.createHasVideoRelation)
router.get('/lap-times/:lapTimeId/has-video', LapTimeController.getAllHasVideoRelations)
router.delete('/lap-times/:lapTimeId/relationships/has-video', LapTimeController.deleteHasVideoRelation)
router.post('/lap-times/:lapTimeId/relationships/has-main-video', LapTimeController.createHasMainVideoRelation)
router.get('/lap-times/:lapTimeId/has-main-video', LapTimeController.getHasMainVideoRelation)
router.delete('/lap-times/:lapTimeId/relationships/has-main-video', LapTimeController.deleteHasMainVideoRelation)

export default router
