import express from "express"
import {MagazineIssueController} from "../../controllers/node-types/MagazineIssueController"

const router = express.Router()

router.post('/magazine-issues', MagazineIssueController.create)
router.get('/magazine-issues/:id', MagazineIssueController.getById)
router.get('/magazine-issues', MagazineIssueController.getAll)
router.patch('/magazine-issues/:id', MagazineIssueController.update)
router.delete('/magazine-issues/:id', MagazineIssueController.delete)
router.post('/magazine-issues/:magazineIssueId/relationships/belongs-to-magazine', MagazineIssueController.createBelongsToMagazineRelation)
router.get('/magazine-issues/:magazineIssueId/belongs-to-magazine', MagazineIssueController.getBelongsToMagazineRelation)
router.delete('/magazine-issues/:magazineIssueId/relationships/belongs-to-magazine', MagazineIssueController.deleteBelongsToMagazineRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/follows-issue', MagazineIssueController.createFollowsIssueRelation)
router.get('/magazine-issues/:magazineIssueId/follows-issue', MagazineIssueController.getFollowsIssueRelation)
router.delete('/magazine-issues/:magazineIssueId/relationships/follows-issue', MagazineIssueController.deleteFollowsIssueRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/followed-by-issue', MagazineIssueController.createFollowedByIssueRelation)
router.get('/magazine-issues/:magazineIssueId/followed-by-issue', MagazineIssueController.getFollowedByIssueRelation)
router.delete('/magazine-issues/:magazineIssueId/relationships/followed-by-issue', MagazineIssueController.deleteFollowedByIssueRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/covers-car-model', MagazineIssueController.createCoversCarModelRelation)
router.get('/magazine-issues/:magazineIssueId/covers-car-model', MagazineIssueController.getAllCoversCarModelRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/covers-car-model', MagazineIssueController.deleteCoversCarModelRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/presents-car-model-variant', MagazineIssueController.createPresentsCarModelVariantRelation)
router.get('/magazine-issues/:magazineIssueId/presents-car-model-variant', MagazineIssueController.getAllPresentsCarModelVariantRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/presents-car-model-variant', MagazineIssueController.deletePresentsCarModelVariantRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/reviewed-car-model-variant-with-rating', MagazineIssueController.createReviewedCarModelVariantWithRatingRelation)
router.get('/magazine-issues/:magazineIssueId/reviewed-car-model-variant-with-rating', MagazineIssueController.getAllReviewedCarModelVariantWithRatingRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/reviewed-car-model-variant-with-rating', MagazineIssueController.deleteReviewedCarModelVariantWithRatingRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/covers-racing-event', MagazineIssueController.createCoversRacingEventRelation)
router.get('/magazine-issues/:magazineIssueId/covers-racing-event', MagazineIssueController.getAllCoversRacingEventRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/covers-racing-event', MagazineIssueController.deleteCoversRacingEventRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/documents-lap-time', MagazineIssueController.createDocumentsLapTimeRelation)
router.get('/magazine-issues/:magazineIssueId/documents-lap-time', MagazineIssueController.getAllDocumentsLapTimeRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/documents-lap-time', MagazineIssueController.deleteDocumentsLapTimeRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/has-image', MagazineIssueController.createHasImageRelation)
router.get('/magazine-issues/:magazineIssueId/has-image', MagazineIssueController.getAllHasImageRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/has-image', MagazineIssueController.deleteHasImageRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/has-prime-image', MagazineIssueController.createHasPrimeImageRelation)
router.get('/magazine-issues/:magazineIssueId/has-prime-image', MagazineIssueController.getHasPrimeImageRelation)
router.delete('/magazine-issues/:magazineIssueId/relationships/has-prime-image', MagazineIssueController.deleteHasPrimeImageRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/has-video', MagazineIssueController.createHasVideoRelation)
router.get('/magazine-issues/:magazineIssueId/has-video', MagazineIssueController.getAllHasVideoRelations)
router.delete('/magazine-issues/:magazineIssueId/relationships/has-video', MagazineIssueController.deleteHasVideoRelation)
router.post('/magazine-issues/:magazineIssueId/relationships/has-main-video', MagazineIssueController.createHasMainVideoRelation)
router.get('/magazine-issues/:magazineIssueId/has-main-video', MagazineIssueController.getHasMainVideoRelation)
router.delete('/magazine-issues/:magazineIssueId/relationships/has-main-video', MagazineIssueController.deleteHasMainVideoRelation)

export default router
