import express from "express"
import {ProgrammeEpisodeController} from "../../controllers/node-types/ProgrammeEpisodeController"

const router = express.Router()

router.post('/programme-episodes', ProgrammeEpisodeController.create)
router.get('/programme-episodes/:id', ProgrammeEpisodeController.getById)
router.get('/programme-episodes', ProgrammeEpisodeController.getAll)
router.patch('/programme-episodes/:id', ProgrammeEpisodeController.update)
router.delete('/programme-episodes/:id', ProgrammeEpisodeController.delete)
router.post('/programme-episodes/:programmeEpisodeId/relationships/belongs-to-programme', ProgrammeEpisodeController.createBelongsToProgrammeRelation)
router.get('/programme-episodes/:programmeEpisodeId/belongs-to-programme', ProgrammeEpisodeController.getBelongsToProgrammeRelation)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/belongs-to-programme', ProgrammeEpisodeController.deleteBelongsToProgrammeRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/follows-episode', ProgrammeEpisodeController.createFollowsEpisodeRelation)
router.get('/programme-episodes/:programmeEpisodeId/follows-episode', ProgrammeEpisodeController.getFollowsEpisodeRelation)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/follows-episode', ProgrammeEpisodeController.deleteFollowsEpisodeRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/is-followed-by-episode', ProgrammeEpisodeController.createIsFollowedByEpisodeRelation)
router.get('/programme-episodes/:programmeEpisodeId/is-followed-by-episode', ProgrammeEpisodeController.getIsFollowedByEpisodeRelation)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/is-followed-by-episode', ProgrammeEpisodeController.deleteIsFollowedByEpisodeRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/covers-car-model', ProgrammeEpisodeController.createCoversCarModelRelation)
router.get('/programme-episodes/:programmeEpisodeId/covers-car-model', ProgrammeEpisodeController.getAllCoversCarModelRelations)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/covers-car-model', ProgrammeEpisodeController.deleteCoversCarModelRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/features-car-model-variant', ProgrammeEpisodeController.createFeaturesCarModelVariantRelation)
router.get('/programme-episodes/:programmeEpisodeId/features-car-model-variant', ProgrammeEpisodeController.getAllFeaturesCarModelVariantRelations)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/features-car-model-variant', ProgrammeEpisodeController.deleteFeaturesCarModelVariantRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/has-image', ProgrammeEpisodeController.createHasImageRelation)
router.get('/programme-episodes/:programmeEpisodeId/has-image', ProgrammeEpisodeController.getAllHasImageRelations)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/has-image', ProgrammeEpisodeController.deleteHasImageRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/has-prime-image', ProgrammeEpisodeController.createHasPrimeImageRelation)
router.get('/programme-episodes/:programmeEpisodeId/has-prime-image', ProgrammeEpisodeController.getHasPrimeImageRelation)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/has-prime-image', ProgrammeEpisodeController.deleteHasPrimeImageRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/has-video', ProgrammeEpisodeController.createHasVideoRelation)
router.get('/programme-episodes/:programmeEpisodeId/has-video', ProgrammeEpisodeController.getAllHasVideoRelations)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/has-video', ProgrammeEpisodeController.deleteHasVideoRelation)
router.post('/programme-episodes/:programmeEpisodeId/relationships/has-main-video', ProgrammeEpisodeController.createHasMainVideoRelation)
router.get('/programme-episodes/:programmeEpisodeId/has-main-video', ProgrammeEpisodeController.getHasMainVideoRelation)
router.delete('/programme-episodes/:programmeEpisodeId/relationships/has-main-video', ProgrammeEpisodeController.deleteHasMainVideoRelation)

export default router
