import express from "express"
import {RacingEventController} from "../../controllers/node-types/RacingEventController"

const router = express.Router()

router.post('/racing-events', RacingEventController.create)
router.get('/racing-events/:id', RacingEventController.getById)
router.get('/racing-events', RacingEventController.getAll)
router.patch('/racing-events/:id', RacingEventController.update)
router.delete('/racing-events/:id', RacingEventController.delete)
router.post('/racing-events/:racingEventId/relationships/belongs-to-racing-series', RacingEventController.createBelongsToRacingSeriesRelation)
router.get('/racing-events/:racingEventId/belongs-to-racing-series', RacingEventController.getBelongsToRacingSeriesRelation)
router.delete('/racing-events/:racingEventId/relationships/belongs-to-racing-series', RacingEventController.deleteBelongsToRacingSeriesRelation)
router.post('/racing-events/:racingEventId/relationships/is-followed-by-event', RacingEventController.createIsFollowedByEventRelation)
router.get('/racing-events/:racingEventId/is-followed-by-event', RacingEventController.getIsFollowedByEventRelation)
router.delete('/racing-events/:racingEventId/relationships/is-followed-by-event', RacingEventController.deleteIsFollowedByEventRelation)
router.post('/racing-events/:racingEventId/relationships/follows-event', RacingEventController.createFollowsEventRelation)
router.get('/racing-events/:racingEventId/follows-event', RacingEventController.getFollowsEventRelation)
router.delete('/racing-events/:racingEventId/relationships/follows-event', RacingEventController.deleteFollowsEventRelation)
router.post('/racing-events/:racingEventId/relationships/took-place-at-race-track', RacingEventController.createTookPlaceAtRaceTrackRelation)
router.get('/racing-events/:racingEventId/took-place-at-race-track', RacingEventController.getTookPlaceAtRaceTrackRelation)
router.delete('/racing-events/:racingEventId/relationships/took-place-at-race-track', RacingEventController.deleteTookPlaceAtRaceTrackRelation)
router.post('/racing-events/:racingEventId/relationships/used-the-track-layout', RacingEventController.createUsedTheTrackLayoutRelation)
router.get('/racing-events/:racingEventId/used-the-track-layout', RacingEventController.getUsedTheTrackLayoutRelation)
router.delete('/racing-events/:racingEventId/relationships/used-the-track-layout', RacingEventController.deleteUsedTheTrackLayoutRelation)
router.post('/racing-events/:racingEventId/relationships/has-racing-session', RacingEventController.createHasRacingSessionRelation)
router.get('/racing-events/:racingEventId/has-racing-session', RacingEventController.getAllHasRacingSessionRelations)
router.delete('/racing-events/:racingEventId/relationships/has-racing-session', RacingEventController.deleteHasRacingSessionRelation)
router.post('/racing-events/:racingEventId/relationships/covered-by-magazine-issue', RacingEventController.createCoveredByMagazineIssueRelation)
router.get('/racing-events/:racingEventId/covered-by-magazine-issue', RacingEventController.getAllCoveredByMagazineIssueRelations)
router.delete('/racing-events/:racingEventId/relationships/covered-by-magazine-issue', RacingEventController.deleteCoveredByMagazineIssueRelation)
router.post('/racing-events/:racingEventId/relationships/has-image', RacingEventController.createHasImageRelation)
router.get('/racing-events/:racingEventId/has-image', RacingEventController.getAllHasImageRelations)
router.delete('/racing-events/:racingEventId/relationships/has-image', RacingEventController.deleteHasImageRelation)
router.post('/racing-events/:racingEventId/relationships/has-prime-image', RacingEventController.createHasPrimeImageRelation)
router.get('/racing-events/:racingEventId/has-prime-image', RacingEventController.getHasPrimeImageRelation)
router.delete('/racing-events/:racingEventId/relationships/has-prime-image', RacingEventController.deleteHasPrimeImageRelation)
router.post('/racing-events/:racingEventId/relationships/has-video', RacingEventController.createHasVideoRelation)
router.get('/racing-events/:racingEventId/has-video', RacingEventController.getAllHasVideoRelations)
router.delete('/racing-events/:racingEventId/relationships/has-video', RacingEventController.deleteHasVideoRelation)
router.post('/racing-events/:racingEventId/relationships/has-main-video', RacingEventController.createHasMainVideoRelation)
router.get('/racing-events/:racingEventId/has-main-video', RacingEventController.getHasMainVideoRelation)
router.delete('/racing-events/:racingEventId/relationships/has-main-video', RacingEventController.deleteHasMainVideoRelation)

export default router
