import express from "express"
import {TrackLayoutController} from "../../controllers/node-types/TrackLayoutController"

const router = express.Router()

router.post('/track-layouts', TrackLayoutController.create)
router.get('/track-layouts/:id', TrackLayoutController.getById)
router.get('/track-layouts', TrackLayoutController.getAll)
router.patch('/track-layouts/:id', TrackLayoutController.update)
router.delete('/track-layouts/:id', TrackLayoutController.delete)
router.post('/track-layouts/:trackLayoutId/relationships/belongs-to-race-track', TrackLayoutController.createBelongsToRaceTrackRelation)
router.get('/track-layouts/:trackLayoutId/belongs-to-race-track', TrackLayoutController.getBelongsToRaceTrackRelation)
router.delete('/track-layouts/:trackLayoutId/relationships/belongs-to-race-track', TrackLayoutController.deleteBelongsToRaceTrackRelation)
router.post('/track-layouts/:trackLayoutId/relationships/was-used-by-racing-event', TrackLayoutController.createWasUsedByRacingEventRelation)
router.get('/track-layouts/:trackLayoutId/was-used-by-racing-event', TrackLayoutController.getAllWasUsedByRacingEventRelations)
router.delete('/track-layouts/:trackLayoutId/relationships/was-used-by-racing-event', TrackLayoutController.deleteWasUsedByRacingEventRelation)
router.post('/track-layouts/:trackLayoutId/relationships/has-lap-time', TrackLayoutController.createHasLapTimeRelation)
router.get('/track-layouts/:trackLayoutId/has-lap-time', TrackLayoutController.getAllHasLapTimeRelations)
router.delete('/track-layouts/:trackLayoutId/relationships/has-lap-time', TrackLayoutController.deleteHasLapTimeRelation)
router.post('/track-layouts/:trackLayoutId/relationships/is-featured-in-racing-game', TrackLayoutController.createIsFeaturedInRacingGameRelation)
router.get('/track-layouts/:trackLayoutId/is-featured-in-racing-game', TrackLayoutController.getAllIsFeaturedInRacingGameRelations)
router.delete('/track-layouts/:trackLayoutId/relationships/is-featured-in-racing-game', TrackLayoutController.deleteIsFeaturedInRacingGameRelation)
router.post('/track-layouts/:trackLayoutId/relationships/has-image', TrackLayoutController.createHasImageRelation)
router.get('/track-layouts/:trackLayoutId/has-image', TrackLayoutController.getAllHasImageRelations)
router.delete('/track-layouts/:trackLayoutId/relationships/has-image', TrackLayoutController.deleteHasImageRelation)
router.post('/track-layouts/:trackLayoutId/relationships/has-prime-image', TrackLayoutController.createHasPrimeImageRelation)
router.get('/track-layouts/:trackLayoutId/has-prime-image', TrackLayoutController.getHasPrimeImageRelation)
router.delete('/track-layouts/:trackLayoutId/relationships/has-prime-image', TrackLayoutController.deleteHasPrimeImageRelation)
router.post('/track-layouts/:trackLayoutId/relationships/has-video', TrackLayoutController.createHasVideoRelation)
router.get('/track-layouts/:trackLayoutId/has-video', TrackLayoutController.getAllHasVideoRelations)
router.delete('/track-layouts/:trackLayoutId/relationships/has-video', TrackLayoutController.deleteHasVideoRelation)
router.post('/track-layouts/:trackLayoutId/relationships/has-main-video', TrackLayoutController.createHasMainVideoRelation)
router.get('/track-layouts/:trackLayoutId/has-main-video', TrackLayoutController.getHasMainVideoRelation)
router.delete('/track-layouts/:trackLayoutId/relationships/has-main-video', TrackLayoutController.deleteHasMainVideoRelation)

export default router
