name: Acceptance Stage

on:
  workflow_call:

jobs:
  commit-stage:
    name: Acceptance Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "acceptance stage..."

