export type CarModelVariantInput = {
    name: string | undefined
    internal_code: string | undefined
    built_from: number | undefined
    built_to: number | undefined
    body_style: string | undefined
    drag_coefficient: number | undefined
    doors: number | undefined
    weight: number | undefined
    weight_unit: string | undefined
    max_power: number | undefined
    max_power_unit: string | undefined
    max_torque: number | undefined
    max_torque_unit: string | undefined
    cylinders: number | undefined
    engine_configuration: string | undefined
    displacement: number | undefined
    displacement_unit: string | undefined
    air_induction: string | undefined
    engine_type: string | undefined
    energy_source: string | undefined
    energy_source_2: string | undefined
    consumption: number | undefined
    consumption_unit: string | undefined
    consumption_2: number | undefined
    consumption_2_unit: string | undefined
    energy_capacity: number | undefined
    energy_capacity_unit: string | undefined
    energy_capacity_2: number | undefined
    energy_capacity_2_unit: string | undefined
    transmission: string | undefined
    gears: number | undefined
    drivetrain: string | undefined
    sprint_time_0_100_kmh: number | undefined
    top_speed: number | undefined
    top_speed_unit: string | undefined
    total_production: number | undefined
}
