import {CarModelVariantNode} from "../../../../models/node-types/car-model-variants/types/CarModelVariantNode"
import {marshalSingleNode} from "../../../nodes/marshalSingleNode"
import {CarModelVariantResponse} from "../types/CarModelVariantResponse"

export function marshalNode(node: CarModelVariantNode) {
    return marshalSingleNode({
        id: node.attributes.id,
        name: node.attributes.name,
        internal_code: node.attributes.internal_code ?? null,
        built_from: node.attributes.built_from ?? null,
        built_to: node.attributes.built_to ?? null,
        body_style: node.attributes.body_style ?? null,
        drag_coefficient: node.attributes.drag_coefficient ?? null,
        doors: node.attributes.doors ?? null,
        weight: node.attributes.weight ?? null,
        weight_unit: node.attributes.weight_unit ?? null,
        max_power: node.attributes.max_power ?? null,
        max_power_unit: node.attributes.max_power_unit ?? null,
        max_torque: node.attributes.max_torque ?? null,
        max_torque_unit: node.attributes.max_torque_unit ?? null,
        cylinders: node.attributes.cylinders ?? null,
        engine_configuration: node.attributes.engine_configuration ?? null,
        displacement: node.attributes.displacement ?? null,
        displacement_unit: node.attributes.displacement_unit ?? null,
        air_induction: node.attributes.air_induction ?? null,
        engine_type: node.attributes.engine_type ?? null,
        energy_source: node.attributes.energy_source ?? null,
        energy_source_2: node.attributes.energy_source_2 ?? null,
        consumption: node.attributes.consumption ?? null,
        consumption_unit: node.attributes.consumption_unit ?? null,
        consumption_2: node.attributes.consumption_2 ?? null,
        consumption_2_unit: node.attributes.consumption_2_unit ?? null,
        energy_capacity: node.attributes.energy_capacity ?? null,
        energy_capacity_unit: node.attributes.energy_capacity_unit ?? null,
        energy_capacity_2: node.attributes.energy_capacity_2 ?? null,
        energy_capacity_2_unit: node.attributes.energy_capacity_2_unit ?? null,
        transmission: node.attributes.transmission ?? null,
        gears: node.attributes.gears ?? null,
        drivetrain: node.attributes.drivetrain ?? null,
        sprint_time_0_100_kmh: node.attributes.sprint_time_0_100_kmh ?? null,
        top_speed: node.attributes.top_speed ?? null,
        top_speed_unit: node.attributes.top_speed_unit ?? null,
        total_production: node.attributes.total_production ?? null,
        created_at: node.attributes.created_at,
        updated_at: node.attributes.updated_at,
    }) as CarModelVariantResponse
}
