import {CreateCarModelVariantRawInput} from "../types/CreateCarModelVariantRawInput"

// @ts-expect-error We cannot set a data type because we don't know what data the user actually provided.
export function unmarshalInputData(data): CreateCarModelVariantRawInput {
    return {
        name: data?.name,
        internal_code: data?.internal_code,
        built_from: data?.built_from,
        built_to: data?.built_to,
        body_style: data?.body_style,
        drag_coefficient: data?.drag_coefficient,
        doors: data?.doors,
        weight: data?.weight,
        weight_unit: data?.weight_unit,
        max_power: data?.max_power,
        max_power_unit: data?.max_power_unit,
        max_torque: data?.max_torque,
        max_torque_unit: data?.max_torque_unit,
        cylinders: data?.cylinders,
        engine_configuration: data?.engine_configuration,
        displacement: data?.displacement,
        displacement_unit: data?.displacement_unit,
        air_induction: data?.air_induction,
        engine_type: data?.engine_type,
        energy_source: data?.energy_source,
        energy_source_2: data?.energy_source_2,
        consumption: data?.consumption,
        consumption_unit: data?.consumption_unit,
        consumption_2: data?.consumption_2,
        consumption_2_unit: data?.consumption_2_unit,
        energy_capacity: data?.energy_capacity,
        energy_capacity_unit: data?.energy_capacity_unit,
        energy_capacity_2: data?.energy_capacity_2,
        energy_capacity_2_unit: data?.energy_capacity_2_unit,
        transmission: data?.transmission,
        gears: data?.gears,
        drivetrain: data?.drivetrain,
        sprint_time_0_100_kmh: data?.sprint_time_0_100_kmh,
        top_speed: data?.top_speed,
        top_speed_unit: data?.top_speed_unit,
        total_production: data?.total_production,
    } as CreateCarModelVariantRawInput
}
