import {expect, test} from 'vitest'
import {unmarshalInputData} from "../../../../../../../src/controllers/nodes/unmarshalInputData"

test('unmarshalling a valid request where optional fields are missing', async () => {
    const data: unknown = {
        name: "BMW M3",
    }

    const result = unmarshalInputData(data, [
        'name',
        'internal_code',
        'built_from',
        'built_to',
        'body_style',
        'drag_coefficient',
        'doors',
        'weight',
        'weight_unit',
        'max_power',
        'max_power_unit',
        'max_torque',
        'max_torque_unit',
        'cylinders',
        'engine_configuration',
        'displacement',
        'displacement_unit',
        'air_induction',
        'engine_type',
        'energy_source',
        'energy_source_2',
        'consumption',
        'consumption_unit',
        'consumption_2',
        'consumption_2_unit',
        'energy_capacity',
        'energy_capacity_unit',
        'energy_capacity_2',
        'energy_capacity_2_unit',
        'transmission',
        'gears',
        'drivetrain',
        'sprint_time_0_100_kmh',
        'top_speed',
        'top_speed_unit',
        'total_production',
    ])

    expect(result)
        .toStrictEqual({
            name: "BMW M3",
            internal_code: undefined,
            built_from: undefined,
            built_to: undefined,
            body_style: undefined,
            drag_coefficient: undefined,
            doors: undefined,
            weight: undefined,
            weight_unit: undefined,
            max_power: undefined,
            max_power_unit: undefined,
            max_torque: undefined,
            max_torque_unit: undefined,
            cylinders: undefined,
            engine_configuration: undefined,
            displacement: undefined,
            displacement_unit: undefined,
            air_induction: undefined,
            engine_type: undefined,
            energy_source: undefined,
            energy_source_2: undefined,
            consumption: undefined,
            consumption_unit: undefined,
            consumption_2: undefined,
            consumption_2_unit: undefined,
            energy_capacity: undefined,
            energy_capacity_unit: undefined,
            energy_capacity_2: undefined,
            energy_capacity_2_unit: undefined,
            transmission: undefined,
            gears: undefined,
            drivetrain: undefined,
            sprint_time_0_100_kmh: undefined,
            top_speed: undefined,
            top_speed_unit: undefined,
            total_production: undefined,
        })
})
