import {expect, test} from 'vitest'
import {unmarshalInputData} from "../../../../../../../src/controllers/nodes/unmarshalInputData"

test('unmarshalling a request where mandatory fields are missing', async () => {
    const data: unknown = {
        internal_code: "E46",
        built_from: 2000,
        built_to: 2006,
        body_style: "coupe",
        drag_coefficient: 0.31,
        doors: 2,
        weight: 1549,
        weight_unit: "kg",
        max_power: 343,
        max_power_unit: "PS",
        max_torque: 365,
        max_torque_unit: "Nm",
        cylinders: 6,
        engine_configuration: "inline",
        displacement: 3246,
        displacement_unit: "ccm",
        air_induction: "naturally aspirated",
        engine_type: "otto",
        energy_source: "petrol",
        energy_source_2: null,
        consumption: 11.9,
        consumption_unit: "l",
        consumption_2: null,
        consumption_2_unit: null,
        energy_capacity: 63,
        energy_capacity_unit: "l",
        energy_capacity_2: null,
        energy_capacity_2_unit: null,
        transmission: "sequential",
        gears: 6,
        drivetrain: "rwd",
        sprint_time_0_100_kmh: 5.2,
        top_speed: 250,
        top_speed_unit: "km/h",
        total_production: 50000,
    }

    const result = unmarshalInputData(data, [
        'name',
        'internal_code',
        'built_from',
        'built_to',
        'body_style',
        'drag_coefficient',
        'doors',
        'weight',
        'weight_unit',
        'max_power',
        'max_power_unit',
        'max_torque',
        'max_torque_unit',
        'cylinders',
        'engine_configuration',
        'displacement',
        'displacement_unit',
        'air_induction',
        'engine_type',
        'energy_source',
        'energy_source_2',
        'consumption',
        'consumption_unit',
        'consumption_2',
        'consumption_2_unit',
        'energy_capacity',
        'energy_capacity_unit',
        'energy_capacity_2',
        'energy_capacity_2_unit',
        'transmission',
        'gears',
        'drivetrain',
        'sprint_time_0_100_kmh',
        'top_speed',
        'top_speed_unit',
        'total_production',
    ])

    expect(result)
        .toStrictEqual({
            name: undefined,
            internal_code: "E46",
            built_from: 2000,
            built_to: 2006,
            body_style: "coupe",
            drag_coefficient: 0.31,
            doors: 2,
            weight: 1549,
            weight_unit: "kg",
            max_power: 343,
            max_power_unit: "PS",
            max_torque: 365,
            max_torque_unit: "Nm",
            cylinders: 6,
            engine_configuration: "inline",
            displacement: 3246,
            displacement_unit: "ccm",
            air_induction: "naturally aspirated",
            engine_type: "otto",
            energy_source: "petrol",
            energy_source_2: null,
            consumption: 11.9,
            consumption_unit: "l",
            consumption_2: null,
            consumption_2_unit: null,
            energy_capacity: 63,
            energy_capacity_unit: "l",
            energy_capacity_2: null,
            energy_capacity_2_unit: null,
            transmission: "sequential",
            gears: 6,
            drivetrain: "rwd",
            sprint_time_0_100_kmh: 5.2,
            top_speed: 250,
            top_speed_unit: "km/h",
            total_production: 50000,
        })
})
