import {RelType} from "../../models/relationships/types/RelType"
import {RelationType} from "../types/RelationType"
import {RelationTypeNotFoundError} from "../types/RelationTypeNotFoundError"

export function mapModelRelationTypeToControllerRelationType(modelRelationshipType: RelType): RelationType {
    const mapping = new Map<RelType, RelationType>([
        [RelType.CompanyHasBrand, RelationType.CompanyHasBrand],
        [RelType.CompanyHasImage, RelationType.CompanyHasImage],
        [RelType.CompanyHasPrimeImage, RelationType.CompanyHasPrimeImage],
        [RelType.CompanyHasVideo, RelationType.CompanyHasVideo],
        [RelType.CompanyHasMainVideo, RelationType.CompanyHasMainVideo],
        [RelType.BrandBelongsToCompany, RelationType.BrandBelongsToCompany],
        [RelType.BrandHasCarModel, RelationType.BrandHasCarModel],
        [RelType.BrandHasImage, RelationType.BrandHasImage],
        [RelType.BrandHasPrimeImage, RelationType.BrandHasPrimeImage],
        [RelType.BrandHasVideo, RelationType.BrandHasVideo],
        [RelType.BrandHasMainVideo, RelationType.BrandHasMainVideo],
        [RelType.CarModelBelongsToBrand, RelationType.CarModelBelongsToBrand],
        [RelType.CarModelHasSuccessor, RelationType.CarModelHasSuccessor],
        [RelType.CarModelIsSuccessorOf, RelationType.CarModelIsSuccessorOf],
        [RelType.CarModelHasVariant, RelationType.CarModelHasVariant],
        [RelType.CarModelCoveredByMagazineIssue, RelationType.CarModelCoveredByMagazineIssue],
        [RelType.CarModelCoveredByProgrammeEpisode, RelationType.CarModelCoveredByProgrammeEpisode],
        [RelType.CarModelHasImage, RelationType.CarModelHasImage],
        [RelType.CarModelHasPrimeImage, RelationType.CarModelHasPrimeImage],
        [RelType.CarModelHasVideo, RelationType.CarModelHasVideo],
        [RelType.CarModelHasMainVideo, RelationType.CarModelHasMainVideo],
        [RelType.CarModelVariantIsVariantOf, RelationType.CarModelVariantIsVariantOf],
        [RelType.CarModelVariantAchievedSessionResult, RelationType.CarModelVariantAchievedSessionResult],
        [RelType.CarModelVariantAchievedLapTime, RelationType.CarModelVariantAchievedLapTime],
        [RelType.CarModelVariantIsPresentedInMagazineIssue, RelationType.CarModelVariantIsPresentedInMagazineIssue],
        [RelType.CarModelVariantReviewedByMagazineIssueWithRating, RelationType.CarModelVariantReviewedByMagazineIssueWithRating],
        [RelType.CarModelVariantFeaturedInProgrammeEpisode, RelationType.CarModelVariantFeaturedInProgrammeEpisode],
        [RelType.CarModelVariantIsFeaturedInRacingGame, RelationType.CarModelVariantIsFeaturedInRacingGame],
        [RelType.CarModelVariantHasScaleModel, RelationType.CarModelVariantHasScaleModel],
        [RelType.CarModelVariantPresentedAtMotorShow, RelationType.CarModelVariantPresentedAtMotorShow],
        [RelType.CarModelVariantHasPrice, RelationType.CarModelVariantHasPrice],
        [RelType.CarModelVariantHasImage, RelationType.CarModelVariantHasImage],
        [RelType.CarModelVariantHasPrimeImage, RelationType.CarModelVariantHasPrimeImage],
        [RelType.CarModelVariantHasVideo, RelationType.CarModelVariantHasVideo],
        [RelType.CarModelVariantHasMainVideo, RelationType.CarModelVariantHasMainVideo],
        [RelType.PriceForCarModelVariant, RelationType.PriceForCarModelVariant],
        [RelType.PriceHasImage, RelationType.PriceHasImage],
        [RelType.PriceHasPrimeImage, RelationType.PriceHasPrimeImage],
        [RelType.RaceTrackHasLayout, RelationType.RaceTrackHasLayout],
        [RelType.RaceTrackHostedRacingEvent, RelationType.RaceTrackHostedRacingEvent],
        [RelType.RaceTrackHasImage, RelationType.RaceTrackHasImage],
        [RelType.RaceTrackHasPrimeImage, RelationType.RaceTrackHasPrimeImage],
        [RelType.RaceTrackHasVideo, RelationType.RaceTrackHasVideo],
        [RelType.RaceTrackHasMainVideo, RelationType.RaceTrackHasMainVideo],
        [RelType.TrackLayoutBelongsToRaceTrack, RelationType.TrackLayoutBelongsToRaceTrack],
        [RelType.TrackLayoutWasUsedByRacingEvent, RelationType.TrackLayoutWasUsedByRacingEvent],
        [RelType.TrackLayoutHasLapTime, RelationType.TrackLayoutHasLapTime],
        [RelType.TrackLayoutIsFeaturedInRacingGame, RelationType.TrackLayoutIsFeaturedInRacingGame],
        [RelType.TrackLayoutHasImage, RelationType.TrackLayoutHasImage],
        [RelType.TrackLayoutHasPrimeImage, RelationType.TrackLayoutHasPrimeImage],
        [RelType.TrackLayoutHasVideo, RelationType.TrackLayoutHasVideo],
        [RelType.TrackLayoutHasMainVideo, RelationType.TrackLayoutHasMainVideo],
        [RelType.RacingSeriesHasRacingEvent, RelationType.RacingSeriesHasRacingEvent],
        [RelType.RacingSeriesHasImage, RelationType.RacingSeriesHasImage],
        [RelType.RacingSeriesHasPrimeImage, RelationType.RacingSeriesHasPrimeImage],
        [RelType.RacingSeriesHasVideo, RelationType.RacingSeriesHasVideo],
        [RelType.RacingSeriesHasMainVideo, RelationType.RacingSeriesHasMainVideo],
        [RelType.RacingEventBelongsToRacingSeries, RelationType.RacingEventBelongsToRacingSeries],
        [RelType.RacingEventIsFollowedByEvent, RelationType.RacingEventIsFollowedByEvent],
        [RelType.RacingEventFollowsEvent, RelationType.RacingEventFollowsEvent],
        [RelType.RacingEventTookPlaceAtRaceTrack, RelationType.RacingEventTookPlaceAtRaceTrack],
        [RelType.RacingEventUsedTheTrackLayout, RelationType.RacingEventUsedTheTrackLayout],
        [RelType.RacingEventHasRacingSession, RelationType.RacingEventHasRacingSession],
        [RelType.RacingEventCoveredByMagazineIssue, RelationType.RacingEventCoveredByMagazineIssue],
        [RelType.RacingEventHasImage, RelationType.RacingEventHasImage],
        [RelType.RacingEventHasPrimeImage, RelationType.RacingEventHasPrimeImage],
        [RelType.RacingEventHasVideo, RelationType.RacingEventHasVideo],
        [RelType.RacingEventHasMainVideo, RelationType.RacingEventHasMainVideo],
        [RelType.RacingSessionBelongsToRacingEvent, RelationType.RacingSessionBelongsToRacingEvent],
        [RelType.RacingSessionHasSessionResult, RelationType.RacingSessionHasSessionResult],
        [RelType.RacingSessionHasImage, RelationType.RacingSessionHasImage],
        [RelType.RacingSessionHasPrimeImage, RelationType.RacingSessionHasPrimeImage],
        [RelType.RacingSessionHasVideo, RelationType.RacingSessionHasVideo],
        [RelType.RacingSessionHasMainVideo, RelationType.RacingSessionHasMainVideo],
        [RelType.SessionResultBelongsToRacingSession, RelationType.SessionResultBelongsToRacingSession],
        [RelType.SessionResultHasLapTime, RelationType.SessionResultHasLapTime],
        [RelType.SessionResultAchievedWithCarModelVariant, RelationType.SessionResultAchievedWithCarModelVariant],
        [RelType.SessionResultHasImage, RelationType.SessionResultHasImage],
        [RelType.SessionResultHasPrimeImage, RelationType.SessionResultHasPrimeImage],
        [RelType.LapTimeBelongsToSessionResult, RelationType.LapTimeBelongsToSessionResult],
        [RelType.LapTimeAchievedOnTrackLayout, RelationType.LapTimeAchievedOnTrackLayout],
        [RelType.LapTimeAchievedWithCarModelVariant, RelationType.LapTimeAchievedWithCarModelVariant],
        [RelType.LapTimeHasImage, RelationType.LapTimeHasImage],
        [RelType.LapTimeHasPrimeImage, RelationType.LapTimeHasPrimeImage],
        [RelType.LapTimeHasVideo, RelationType.LapTimeHasVideo],
        [RelType.LapTimeHasMainVideo, RelationType.LapTimeHasMainVideo],
        [RelType.RacingGameFeaturesCarModelVariant, RelationType.RacingGameFeaturesCarModelVariant],
        [RelType.RacingGameFeaturesTrackLayout, RelationType.RacingGameFeaturesTrackLayout],
        [RelType.RacingGameReleasedOnGamingPlatform, RelationType.RacingGameReleasedOnGamingPlatform],
        [RelType.RacingGameHasImage, RelationType.RacingGameHasImage],
        [RelType.RacingGameHasPrimeImage, RelationType.RacingGameHasPrimeImage],
        [RelType.RacingGameHasVideo, RelationType.RacingGameHasVideo],
        [RelType.RacingGameHasMainVideo, RelationType.RacingGameHasMainVideo],
        [RelType.GamingPlatformFeaturesRacingGame, RelationType.GamingPlatformFeaturesRacingGame],
        [RelType.GamingPlatformHasImage, RelationType.GamingPlatformHasImage],
        [RelType.GamingPlatformHasPrimeImage, RelationType.GamingPlatformHasPrimeImage],
        [RelType.GamingPlatformHasVideo, RelationType.GamingPlatformHasVideo],
        [RelType.GamingPlatformHasMainVideo, RelationType.GamingPlatformHasMainVideo],
        [RelType.ModelCarIsScaleModelOfCarModelVariant, RelationType.ModelCarIsScaleModelOfCarModelVariant],
        [RelType.ModelCarMadeByModelCarBrand, RelationType.ModelCarMadeByModelCarBrand],
        [RelType.ModelCarHasImage, RelationType.ModelCarHasImage],
        [RelType.ModelCarHasPrimeImage, RelationType.ModelCarHasPrimeImage],
        [RelType.ModelCarHasVideo, RelationType.ModelCarHasVideo],
        [RelType.ModelCarHasMainVideo, RelationType.ModelCarHasMainVideo],
        [RelType.ModelCarBrandCreatedModelCar, RelationType.ModelCarBrandCreatedModelCar],
        [RelType.ModelCarBrandHasImage, RelationType.ModelCarBrandHasImage],
        [RelType.ModelCarBrandHasPrimeImage, RelationType.ModelCarBrandHasPrimeImage],
        [RelType.ImageBelongsToNode, RelationType.ImageBelongsToNode],
        [RelType.MagazineHasIssue, RelationType.MagazineHasIssue],
        [RelType.MagazineHasImage, RelationType.MagazineHasImage],
        [RelType.MagazineHasPrimeImage, RelationType.MagazineHasPrimeImage],
        [RelType.MagazineIssueBelongsToMagazine, RelationType.MagazineIssueBelongsToMagazine],
        [RelType.MagazineIssueFollowsIssue, RelationType.MagazineIssueFollowsIssue],
        [RelType.MagazineIssueFollowedByIssue, RelationType.MagazineIssueFollowedByIssue],
        [RelType.MagazineIssueCoversCarModel, RelationType.MagazineIssueCoversCarModel],
        [RelType.MagazineIssuePresentsCarModelVariant, RelationType.MagazineIssuePresentsCarModelVariant],
        [RelType.MagazineIssueReviewedCarModelVariantWithRating, RelationType.MagazineIssueReviewedCarModelVariantWithRating],
        [RelType.MagazineIssueCoversRacingEvent, RelationType.MagazineIssueCoversRacingEvent],
        [RelType.MagazineIssueHasImage, RelationType.MagazineIssueHasImage],
        [RelType.MagazineIssueHasPrimeImage, RelationType.MagazineIssueHasPrimeImage],
        [RelType.RatingByMagazineIssue, RelationType.RatingByMagazineIssue],
        [RelType.RatingForCarModelVariant, RelationType.RatingForCarModelVariant],
        [RelType.RatingHasImage, RelationType.RatingHasImage],
        [RelType.RatingHasPrimeImage, RelationType.RatingHasPrimeImage],
        [RelType.ProgrammeHasEpisode, RelationType.ProgrammeHasEpisode],
        [RelType.ProgrammeHasImage, RelationType.ProgrammeHasImage],
        [RelType.ProgrammeHasPrimeImage, RelationType.ProgrammeHasPrimeImage],
        [RelType.ProgrammeEpisodeBelongsToProgramme, RelationType.ProgrammeEpisodeBelongsToProgramme],
        [RelType.ProgrammeEpisodeFollowsEpisode, RelationType.ProgrammeEpisodeFollowsEpisode],
        [RelType.ProgrammeEpisodeIsFollowedByEpisode, RelationType.ProgrammeEpisodeIsFollowedByEpisode],
        [RelType.ProgrammeEpisodeCoversCarModel, RelationType.ProgrammeEpisodeCoversCarModel],
        [RelType.ProgrammeEpisodeFeaturesCarModelVariant, RelationType.ProgrammeEpisodeFeaturesCarModelVariant],
        [RelType.ProgrammeEpisodeHasImage, RelationType.ProgrammeEpisodeHasImage],
        [RelType.ProgrammeEpisodeHasPrimeImage, RelationType.ProgrammeEpisodeHasPrimeImage],
        [RelType.MotorShowPresentsCarModelVariant, RelationType.MotorShowPresentsCarModelVariant],
        [RelType.MotorShowHasImage, RelationType.MotorShowHasImage],
        [RelType.MotorShowHasPrimeImage, RelationType.MotorShowHasPrimeImage],
        [RelType.VideoBelongsToNode, RelationType.VideoBelongsToNode],
        [RelType.VideoIsMainVideoOfNode, RelationType.VideoIsMainVideoOfNode],
        [RelType.ImageIsPrimeImageOfNode, RelationType.ImageIsPrimeImageOfNode],
    ])

    const mappedRel = mapping.get(modelRelationshipType)

    if (!mappedRel) {
        throw new RelationTypeNotFoundError(modelRelationshipType)
    }

    return mappedRel
}
