exports.Companies = require('./Companies.js')
exports.Brands = require('./Brands.js')
exports.CarModels = require('./CarModels.js')
exports.Images = require('./Images.js')
exports.Relationships = require('./Relationships.js')
