import {RelationshipType as DbRelationshipType} from "../db/types/RelationshipType"
import {RelationshipType} from "./RelationshipType"
import {RelationshipTypeMappingNotFoundError} from "./RelationshipTypeMappingNotFoundError"

export function mapDbRelationshipTypeToRelationshipType(dbRelationshipType: DbRelationshipType): RelationshipType {
    const mapping = new Map<DbRelationshipType, RelationshipType>([
        [DbRelationshipType.NodeHasImage, RelationshipType.NodeHasImage],
        [DbRelationshipType.NodeHasPrimeImage, RelationshipType.NodeHasPrimeImage],
        [DbRelationshipType.CompanyHasBrand, RelationshipType.CompanyHasBrand],
        [DbRelationshipType.CompanyHasImage, RelationshipType.CompanyHasImage],
        [DbRelationshipType.CompanyHasPrimeImage, RelationshipType.CompanyHasPrimeImage],
        [DbRelationshipType.CompanyHasVideo, RelationshipType.CompanyHasVideo],
        [DbRelationshipType.CompanyHasMainVideo, RelationshipType.CompanyHasMainVideo],
        [DbRelationshipType.BrandBelongsToCompany, RelationshipType.BrandBelongsToCompany],
        [DbRelationshipType.BrandHasCarModel, RelationshipType.BrandHasCarModel],
        [DbRelationshipType.BrandHasImage, RelationshipType.BrandHasImage],
        [DbRelationshipType.BrandHasPrimeImage, RelationshipType.BrandHasPrimeImage],
        [DbRelationshipType.BrandHasVideo, RelationshipType.BrandHasVideo],
        [DbRelationshipType.BrandHasMainVideo, RelationshipType.BrandHasMainVideo],
        [DbRelationshipType.CarModelBelongsToBrand, RelationshipType.CarModelBelongsToBrand],
        [DbRelationshipType.CarModelHasSuccessor, RelationshipType.CarModelHasSuccessor],
        [DbRelationshipType.CarModelIsSuccessorOf, RelationshipType.CarModelIsSuccessorOf],
        [DbRelationshipType.CarModelHasVariant, RelationshipType.CarModelHasVariant],
        [DbRelationshipType.CarModelCoveredByMagazineIssue, RelationshipType.CarModelCoveredByMagazineIssue],
        [DbRelationshipType.CarModelCoveredByProgrammeEpisode, RelationshipType.CarModelCoveredByProgrammeEpisode],
        [DbRelationshipType.CarModelHasImage, RelationshipType.CarModelHasImage],
        [DbRelationshipType.CarModelHasPrimeImage, RelationshipType.CarModelHasPrimeImage],
        [DbRelationshipType.CarModelHasVideo, RelationshipType.CarModelHasVideo],
        [DbRelationshipType.CarModelHasMainVideo, RelationshipType.CarModelHasMainVideo],
        [DbRelationshipType.CarModelVariantIsVariantOf, RelationshipType.CarModelVariantIsVariantOf],
        [DbRelationshipType.CarModelVariantAchievedSessionResult, RelationshipType.CarModelVariantAchievedSessionResult],
        [DbRelationshipType.CarModelVariantAchievedLapTime, RelationshipType.CarModelVariantAchievedLapTime],
        [DbRelationshipType.CarModelVariantIsPresentedInMagazineIssue, RelationshipType.CarModelVariantIsPresentedInMagazineIssue],
        [DbRelationshipType.CarModelVariantReviewedByMagazineIssueWithRating, RelationshipType.CarModelVariantReviewedByMagazineIssueWithRating],
        [DbRelationshipType.CarModelVariantFeaturedInProgrammeEpisode, RelationshipType.CarModelVariantFeaturedInProgrammeEpisode],
        [DbRelationshipType.CarModelVariantIsFeaturedInRacingGame, RelationshipType.CarModelVariantIsFeaturedInRacingGame],
        [DbRelationshipType.CarModelVariantHasScaleModel, RelationshipType.CarModelVariantHasScaleModel],
        [DbRelationshipType.CarModelVariantPresentedAtMotorShow, RelationshipType.CarModelVariantPresentedAtMotorShow],
        [DbRelationshipType.CarModelVariantHasPrice, RelationshipType.CarModelVariantHasPrice],
        [DbRelationshipType.CarModelVariantHasImage, RelationshipType.CarModelVariantHasImage],
        [DbRelationshipType.CarModelVariantHasPrimeImage, RelationshipType.CarModelVariantHasPrimeImage],
        [DbRelationshipType.CarModelVariantHasVideo, RelationshipType.CarModelVariantHasVideo],
        [DbRelationshipType.CarModelVariantHasMainVideo, RelationshipType.CarModelVariantHasMainVideo],
        [DbRelationshipType.PriceForCarModelVariant, RelationshipType.PriceForCarModelVariant],
        [DbRelationshipType.PriceHasImage, RelationshipType.PriceHasImage],
        [DbRelationshipType.PriceHasPrimeImage, RelationshipType.PriceHasPrimeImage],
        [DbRelationshipType.RaceTrackHasLayout, RelationshipType.RaceTrackHasLayout],
        [DbRelationshipType.RaceTrackHostedRacingEvent, RelationshipType.RaceTrackHostedRacingEvent],
        [DbRelationshipType.RaceTrackHasImage, RelationshipType.RaceTrackHasImage],
        [DbRelationshipType.RaceTrackHasPrimeImage, RelationshipType.RaceTrackHasPrimeImage],
        [DbRelationshipType.RaceTrackHasVideo, RelationshipType.RaceTrackHasVideo],
        [DbRelationshipType.RaceTrackHasMainVideo, RelationshipType.RaceTrackHasMainVideo],
        [DbRelationshipType.TrackLayoutBelongsToRaceTrack, RelationshipType.TrackLayoutBelongsToRaceTrack],
        [DbRelationshipType.TrackLayoutWasUsedByRacingEvent, RelationshipType.TrackLayoutWasUsedByRacingEvent],
        [DbRelationshipType.TrackLayoutHasLapTime, RelationshipType.TrackLayoutHasLapTime],
        [DbRelationshipType.TrackLayoutIsFeaturedInRacingGame, RelationshipType.TrackLayoutIsFeaturedInRacingGame],
        [DbRelationshipType.TrackLayoutHasImage, RelationshipType.TrackLayoutHasImage],
        [DbRelationshipType.TrackLayoutHasPrimeImage, RelationshipType.TrackLayoutHasPrimeImage],
        [DbRelationshipType.TrackLayoutHasVideo, RelationshipType.TrackLayoutHasVideo],
        [DbRelationshipType.TrackLayoutHasMainVideo, RelationshipType.TrackLayoutHasMainVideo],
        [DbRelationshipType.RacingSeriesHasRacingEvent, RelationshipType.RacingSeriesHasRacingEvent],
        [DbRelationshipType.RacingSeriesHasImage, RelationshipType.RacingSeriesHasImage],
        [DbRelationshipType.RacingSeriesHasPrimeImage, RelationshipType.RacingSeriesHasPrimeImage],
        [DbRelationshipType.RacingSeriesHasVideo, RelationshipType.RacingSeriesHasVideo],
        [DbRelationshipType.RacingSeriesHasMainVideo, RelationshipType.RacingSeriesHasMainVideo],
        [DbRelationshipType.RacingEventBelongsToRacingSeries, RelationshipType.RacingEventBelongsToRacingSeries],
        [DbRelationshipType.RacingEventIsFollowedByEvent, RelationshipType.RacingEventIsFollowedByEvent],
        [DbRelationshipType.RacingEventFollowsEvent, RelationshipType.RacingEventFollowsEvent],
        [DbRelationshipType.RacingEventTookPlaceAtRaceTrack, RelationshipType.RacingEventTookPlaceAtRaceTrack],
        [DbRelationshipType.RacingEventUsedTheTrackLayout, RelationshipType.RacingEventUsedTheTrackLayout],
        [DbRelationshipType.RacingEventHasRacingSession, RelationshipType.RacingEventHasRacingSession],
        [DbRelationshipType.RacingEventCoveredByMagazineIssue, RelationshipType.RacingEventCoveredByMagazineIssue],
        [DbRelationshipType.RacingEventHasImage, RelationshipType.RacingEventHasImage],
        [DbRelationshipType.RacingEventHasPrimeImage, RelationshipType.RacingEventHasPrimeImage],
        [DbRelationshipType.RacingEventHasVideo, RelationshipType.RacingEventHasVideo],
        [DbRelationshipType.RacingEventHasMainVideo, RelationshipType.RacingEventHasMainVideo],
        [DbRelationshipType.RacingSessionBelongsToRacingEvent, RelationshipType.RacingSessionBelongsToRacingEvent],
        [DbRelationshipType.RacingSessionHasSessionResult, RelationshipType.RacingSessionHasSessionResult],
        [DbRelationshipType.RacingSessionHasImage, RelationshipType.RacingSessionHasImage],
        [DbRelationshipType.RacingSessionHasPrimeImage, RelationshipType.RacingSessionHasPrimeImage],
        [DbRelationshipType.SessionResultBelongsToRacingSession, RelationshipType.SessionResultBelongsToRacingSession],
        [DbRelationshipType.SessionResultHasLapTime, RelationshipType.SessionResultHasLapTime],
        [DbRelationshipType.SessionResultAchievedWithCarModelVariant, RelationshipType.SessionResultAchievedWithCarModelVariant],
        [DbRelationshipType.SessionResultHasImage, RelationshipType.SessionResultHasImage],
        [DbRelationshipType.SessionResultHasPrimeImage, RelationshipType.SessionResultHasPrimeImage],
        [DbRelationshipType.LapTimeBelongsToSessionResult, RelationshipType.LapTimeBelongsToSessionResult],
        [DbRelationshipType.LapTimeAchievedOnTrackLayout, RelationshipType.LapTimeAchievedOnTrackLayout],
        [DbRelationshipType.LapTimeAchievedWithCarModelVariant, RelationshipType.LapTimeAchievedWithCarModelVariant],
        [DbRelationshipType.LapTimeHasImage, RelationshipType.LapTimeHasImage],
        [DbRelationshipType.LapTimeHasPrimeImage, RelationshipType.LapTimeHasPrimeImage],
        [DbRelationshipType.RacingGameFeaturesCarModelVariant, RelationshipType.RacingGameFeaturesCarModelVariant],
        [DbRelationshipType.RacingGameFeaturesTrackLayout, RelationshipType.RacingGameFeaturesTrackLayout],
        [DbRelationshipType.RacingGameReleasedOnGamingPlatform, RelationshipType.RacingGameReleasedOnGamingPlatform],
        [DbRelationshipType.RacingGameHasImage, RelationshipType.RacingGameHasImage],
        [DbRelationshipType.RacingGameHasPrimeImage, RelationshipType.RacingGameHasPrimeImage],
        [DbRelationshipType.RacingGameHasVideo, RelationshipType.RacingGameHasVideo],
        [DbRelationshipType.RacingGameHasMainVideo, RelationshipType.RacingGameHasMainVideo],
        [DbRelationshipType.GamingPlatformFeaturesRacingGame, RelationshipType.GamingPlatformFeaturesRacingGame],
        [DbRelationshipType.GamingPlatformHasImage, RelationshipType.GamingPlatformHasImage],
        [DbRelationshipType.GamingPlatformHasPrimeImage, RelationshipType.GamingPlatformHasPrimeImage],
        [DbRelationshipType.GamingPlatformHasVideo, RelationshipType.GamingPlatformHasVideo],
        [DbRelationshipType.GamingPlatformHasMainVideo, RelationshipType.GamingPlatformHasMainVideo],
        [DbRelationshipType.ModelCarIsScaleModelOfCarModelVariant, RelationshipType.ModelCarIsScaleModelOfCarModelVariant],
        [DbRelationshipType.ModelCarMadeByModelCarBrand, RelationshipType.ModelCarMadeByModelCarBrand],
        [DbRelationshipType.ModelCarHasImage, RelationshipType.ModelCarHasImage],
        [DbRelationshipType.ModelCarHasPrimeImage, RelationshipType.ModelCarHasPrimeImage],
        [DbRelationshipType.ModelCarBrandCreatedModelCar, RelationshipType.ModelCarBrandCreatedModelCar],
        [DbRelationshipType.ModelCarBrandHasImage, RelationshipType.ModelCarBrandHasImage],
        [DbRelationshipType.ModelCarBrandHasPrimeImage, RelationshipType.ModelCarBrandHasPrimeImage],
        [DbRelationshipType.MagazineHasIssue, RelationshipType.MagazineHasIssue],
        [DbRelationshipType.MagazineHasImage, RelationshipType.MagazineHasImage],
        [DbRelationshipType.MagazineHasPrimeImage, RelationshipType.MagazineHasPrimeImage],
        [DbRelationshipType.MagazineIssueBelongsToMagazine, RelationshipType.MagazineIssueBelongsToMagazine],
        [DbRelationshipType.MagazineIssueFollowsIssue, RelationshipType.MagazineIssueFollowsIssue],
        [DbRelationshipType.MagazineIssueFollowedByIssue, RelationshipType.MagazineIssueFollowedByIssue],
        [DbRelationshipType.MagazineIssueCoversCarModel, RelationshipType.MagazineIssueCoversCarModel],
        [DbRelationshipType.MagazineIssuePresentsCarModelVariant, RelationshipType.MagazineIssuePresentsCarModelVariant],
        [DbRelationshipType.MagazineIssueReviewedCarModelVariantWithRating, RelationshipType.MagazineIssueReviewedCarModelVariantWithRating],
        [DbRelationshipType.MagazineIssueCoversRacingEvent, RelationshipType.MagazineIssueCoversRacingEvent],
        [DbRelationshipType.MagazineIssueHasImage, RelationshipType.MagazineIssueHasImage],
        [DbRelationshipType.MagazineIssueHasPrimeImage, RelationshipType.MagazineIssueHasPrimeImage],
        [DbRelationshipType.RatingByMagazineIssue, RelationshipType.RatingByMagazineIssue],
        [DbRelationshipType.RatingForCarModelVariant, RelationshipType.RatingForCarModelVariant],
        [DbRelationshipType.RatingHasImage, RelationshipType.RatingHasImage],
        [DbRelationshipType.RatingHasPrimeImage, RelationshipType.RatingHasPrimeImage],
        [DbRelationshipType.ProgrammeHasEpisode, RelationshipType.ProgrammeHasEpisode],
        [DbRelationshipType.ProgrammeHasImage, RelationshipType.ProgrammeHasImage],
        [DbRelationshipType.ProgrammeHasPrimeImage, RelationshipType.ProgrammeHasPrimeImage],
        [DbRelationshipType.ProgrammeEpisodeBelongsToProgramme, RelationshipType.ProgrammeEpisodeBelongsToProgramme],
        [DbRelationshipType.ProgrammeEpisodeFollowsEpisode, RelationshipType.ProgrammeEpisodeFollowsEpisode],
        [DbRelationshipType.ProgrammeEpisodeIsFollowedByEpisode, RelationshipType.ProgrammeEpisodeIsFollowedByEpisode],
        [DbRelationshipType.ProgrammeEpisodeCoversCarModel, RelationshipType.ProgrammeEpisodeCoversCarModel],
        [DbRelationshipType.ProgrammeEpisodeFeaturesCarModelVariant, RelationshipType.ProgrammeEpisodeFeaturesCarModelVariant],
        [DbRelationshipType.ProgrammeEpisodeHasImage, RelationshipType.ProgrammeEpisodeHasImage],
        [DbRelationshipType.ProgrammeEpisodeHasPrimeImage, RelationshipType.ProgrammeEpisodeHasPrimeImage],
        [DbRelationshipType.MotorShowPresentsCarModelVariant, RelationshipType.MotorShowPresentsCarModelVariant],
        [DbRelationshipType.MotorShowHasImage, RelationshipType.MotorShowHasImage],
        [DbRelationshipType.MotorShowHasPrimeImage, RelationshipType.MotorShowHasPrimeImage],
        [DbRelationshipType.VideoBelongsToNode, RelationshipType.VideoBelongsToNode],
        [DbRelationshipType.VideoIsMainVideoOfNode, RelationshipType.VideoIsMainVideoOfNode],
        [DbRelationshipType.ImageBelongsToNode, RelationshipType.ImageBelongsToNode],
        [DbRelationshipType.ImageIsPrimeImageOfNode, RelationshipType.ImageIsPrimeImageOfNode],
    ])

    const relationshipType = mapping.get(dbRelationshipType)

    if (!relationshipType) {
        throw new RelationshipTypeMappingNotFoundError(dbRelationshipType)
    }

    return relationshipType
}
