import {RelType} from "../models/relationships/types/RelType"
import {RelationshipType} from "./RelationshipType"
import {RelationshipTypeMappingNotFoundError} from "./RelationshipTypeMappingNotFoundError"

export function mapModelRelationshipTypeToRelationshipType(relType: RelType): RelationshipType {
    const mapping = new Map<RelType, RelationshipType>([
        [RelType.CompanyHasBrand, RelationshipType.CompanyHasBrand],
        [RelType.CompanyHasImage, RelationshipType.CompanyHasImage],
        [RelType.CompanyHasPrimeImage, RelationshipType.CompanyHasPrimeImage],
        [RelType.CompanyHasVideo, RelationshipType.CompanyHasVideo],
        [RelType.CompanyHasMainVideo, RelationshipType.CompanyHasMainVideo],
        [RelType.BrandBelongsToCompany, RelationshipType.BrandBelongsToCompany],
        [RelType.BrandHasCarModel, RelationshipType.BrandHasCarModel],
        [RelType.BrandHasImage, RelationshipType.BrandHasImage],
        [RelType.BrandHasPrimeImage, RelationshipType.BrandHasPrimeImage],
        [RelType.BrandHasVideo, RelationshipType.BrandHasVideo],
        [RelType.BrandHasMainVideo, RelationshipType.BrandHasMainVideo],
        [RelType.CarModelBelongsToBrand, RelationshipType.CarModelBelongsToBrand],
        [RelType.CarModelHasSuccessor, RelationshipType.CarModelHasSuccessor],
        [RelType.CarModelIsSuccessorOf, RelationshipType.CarModelIsSuccessorOf],
        [RelType.CarModelHasVariant, RelationshipType.CarModelHasVariant],
        [RelType.CarModelCoveredByMagazineIssue, RelationshipType.CarModelCoveredByMagazineIssue],
        [RelType.CarModelCoveredByProgrammeEpisode, RelationshipType.CarModelCoveredByProgrammeEpisode],
        [RelType.CarModelHasImage, RelationshipType.CarModelHasImage],
        [RelType.CarModelHasPrimeImage, RelationshipType.CarModelHasPrimeImage],
        [RelType.CarModelHasVideo, RelationshipType.CarModelHasVideo],
        [RelType.CarModelHasMainVideo, RelationshipType.CarModelHasMainVideo],
        [RelType.CarModelVariantIsVariantOf, RelationshipType.CarModelVariantIsVariantOf],
        [RelType.CarModelVariantAchievedSessionResult, RelationshipType.CarModelVariantAchievedSessionResult],
        [RelType.CarModelVariantAchievedLapTime, RelationshipType.CarModelVariantAchievedLapTime],
        [RelType.CarModelVariantIsPresentedInMagazineIssue, RelationshipType.CarModelVariantIsPresentedInMagazineIssue],
        [RelType.CarModelVariantReviewedByMagazineIssueWithRating, RelationshipType.CarModelVariantReviewedByMagazineIssueWithRating],
        [RelType.CarModelVariantFeaturedInProgrammeEpisode, RelationshipType.CarModelVariantFeaturedInProgrammeEpisode],
        [RelType.CarModelVariantIsFeaturedInRacingGame, RelationshipType.CarModelVariantIsFeaturedInRacingGame],
        [RelType.CarModelVariantHasScaleModel, RelationshipType.CarModelVariantHasScaleModel],
        [RelType.CarModelVariantPresentedAtMotorShow, RelationshipType.CarModelVariantPresentedAtMotorShow],
        [RelType.CarModelVariantHasPrice, RelationshipType.CarModelVariantHasPrice],
        [RelType.CarModelVariantHasImage, RelationshipType.CarModelVariantHasImage],
        [RelType.CarModelVariantHasPrimeImage, RelationshipType.CarModelVariantHasPrimeImage],
        [RelType.CarModelVariantHasVideo, RelationshipType.CarModelVariantHasVideo],
        [RelType.CarModelVariantHasMainVideo, RelationshipType.CarModelVariantHasMainVideo],
        [RelType.PriceForCarModelVariant, RelationshipType.PriceForCarModelVariant],
        [RelType.PriceHasImage, RelationshipType.PriceHasImage],
        [RelType.PriceHasPrimeImage, RelationshipType.PriceHasPrimeImage],
        [RelType.RaceTrackHasLayout, RelationshipType.RaceTrackHasLayout],
        [RelType.RaceTrackHostedRacingEvent, RelationshipType.RaceTrackHostedRacingEvent],
        [RelType.RaceTrackHasImage, RelationshipType.RaceTrackHasImage],
        [RelType.RaceTrackHasPrimeImage, RelationshipType.RaceTrackHasPrimeImage],
        [RelType.RaceTrackHasVideo, RelationshipType.RaceTrackHasVideo],
        [RelType.RaceTrackHasMainVideo, RelationshipType.RaceTrackHasMainVideo],
        [RelType.TrackLayoutBelongsToRaceTrack, RelationshipType.TrackLayoutBelongsToRaceTrack],
        [RelType.TrackLayoutWasUsedByRacingEvent, RelationshipType.TrackLayoutWasUsedByRacingEvent],
        [RelType.TrackLayoutHasLapTime, RelationshipType.TrackLayoutHasLapTime],
        [RelType.TrackLayoutIsFeaturedInRacingGame, RelationshipType.TrackLayoutIsFeaturedInRacingGame],
        [RelType.TrackLayoutHasImage, RelationshipType.TrackLayoutHasImage],
        [RelType.TrackLayoutHasPrimeImage, RelationshipType.TrackLayoutHasPrimeImage],
        [RelType.TrackLayoutHasVideo, RelationshipType.TrackLayoutHasVideo],
        [RelType.TrackLayoutHasMainVideo, RelationshipType.TrackLayoutHasMainVideo],
        [RelType.RacingSeriesHasRacingEvent, RelationshipType.RacingSeriesHasRacingEvent],
        [RelType.RacingSeriesHasImage, RelationshipType.RacingSeriesHasImage],
        [RelType.RacingSeriesHasPrimeImage, RelationshipType.RacingSeriesHasPrimeImage],
        [RelType.RacingSeriesHasVideo, RelationshipType.RacingSeriesHasVideo],
        [RelType.RacingSeriesHasMainVideo, RelationshipType.RacingSeriesHasMainVideo],
        [RelType.RacingEventBelongsToRacingSeries, RelationshipType.RacingEventBelongsToRacingSeries],
        [RelType.RacingEventIsFollowedByEvent, RelationshipType.RacingEventIsFollowedByEvent],
        [RelType.RacingEventFollowsEvent, RelationshipType.RacingEventFollowsEvent],
        [RelType.RacingEventTookPlaceAtRaceTrack, RelationshipType.RacingEventTookPlaceAtRaceTrack],
        [RelType.RacingEventUsedTheTrackLayout, RelationshipType.RacingEventUsedTheTrackLayout],
        [RelType.RacingEventHasRacingSession, RelationshipType.RacingEventHasRacingSession],
        [RelType.RacingEventCoveredByMagazineIssue, RelationshipType.RacingEventCoveredByMagazineIssue],
        [RelType.RacingEventHasImage, RelationshipType.RacingEventHasImage],
        [RelType.RacingEventHasPrimeImage, RelationshipType.RacingEventHasPrimeImage],
        [RelType.RacingEventHasVideo, RelationshipType.RacingEventHasVideo],
        [RelType.RacingEventHasMainVideo, RelationshipType.RacingEventHasMainVideo],
        [RelType.RacingSessionBelongsToRacingEvent, RelationshipType.RacingSessionBelongsToRacingEvent],
        [RelType.RacingSessionHasSessionResult, RelationshipType.RacingSessionHasSessionResult],
        [RelType.RacingSessionHasImage, RelationshipType.RacingSessionHasImage],
        [RelType.RacingSessionHasPrimeImage, RelationshipType.RacingSessionHasPrimeImage],
        [RelType.RacingSessionHasVideo, RelationshipType.RacingSessionHasVideo],
        [RelType.RacingSessionHasMainVideo, RelationshipType.RacingSessionHasMainVideo],
        [RelType.SessionResultBelongsToRacingSession, RelationshipType.SessionResultBelongsToRacingSession],
        [RelType.SessionResultHasLapTime, RelationshipType.SessionResultHasLapTime],
        [RelType.SessionResultAchievedWithCarModelVariant, RelationshipType.SessionResultAchievedWithCarModelVariant],
        [RelType.SessionResultHasImage, RelationshipType.SessionResultHasImage],
        [RelType.SessionResultHasPrimeImage, RelationshipType.SessionResultHasPrimeImage],
        [RelType.LapTimeBelongsToSessionResult, RelationshipType.LapTimeBelongsToSessionResult],
        [RelType.LapTimeAchievedOnTrackLayout, RelationshipType.LapTimeAchievedOnTrackLayout],
        [RelType.LapTimeAchievedWithCarModelVariant, RelationshipType.LapTimeAchievedWithCarModelVariant],
        [RelType.LapTimeHasImage, RelationshipType.LapTimeHasImage],
        [RelType.LapTimeHasPrimeImage, RelationshipType.LapTimeHasPrimeImage],
        [RelType.LapTimeHasVideo, RelationshipType.LapTimeHasVideo],
        [RelType.LapTimeHasMainVideo, RelationshipType.LapTimeHasMainVideo],
        [RelType.RacingGameFeaturesCarModelVariant, RelationshipType.RacingGameFeaturesCarModelVariant],
        [RelType.RacingGameFeaturesTrackLayout, RelationshipType.RacingGameFeaturesTrackLayout],
        [RelType.RacingGameReleasedOnGamingPlatform, RelationshipType.RacingGameReleasedOnGamingPlatform],
        [RelType.RacingGameHasImage, RelationshipType.RacingGameHasImage],
        [RelType.RacingGameHasPrimeImage, RelationshipType.RacingGameHasPrimeImage],
        [RelType.RacingGameHasVideo, RelationshipType.RacingGameHasVideo],
        [RelType.RacingGameHasMainVideo, RelationshipType.RacingGameHasMainVideo],
        [RelType.GamingPlatformFeaturesRacingGame, RelationshipType.GamingPlatformFeaturesRacingGame],
        [RelType.GamingPlatformHasImage, RelationshipType.GamingPlatformHasImage],
        [RelType.GamingPlatformHasPrimeImage, RelationshipType.GamingPlatformHasPrimeImage],
        [RelType.GamingPlatformHasVideo, RelationshipType.GamingPlatformHasVideo],
        [RelType.GamingPlatformHasMainVideo, RelationshipType.GamingPlatformHasMainVideo],
        [RelType.ModelCarIsScaleModelOfCarModelVariant, RelationshipType.ModelCarIsScaleModelOfCarModelVariant],
        [RelType.ModelCarMadeByModelCarBrand, RelationshipType.ModelCarMadeByModelCarBrand],
        [RelType.ModelCarHasImage, RelationshipType.ModelCarHasImage],
        [RelType.ModelCarHasPrimeImage, RelationshipType.ModelCarHasPrimeImage],
        [RelType.ModelCarBrandCreatedModelCar, RelationshipType.ModelCarBrandCreatedModelCar],
        [RelType.ModelCarBrandHasImage, RelationshipType.ModelCarBrandHasImage],
        [RelType.ModelCarBrandHasPrimeImage, RelationshipType.ModelCarBrandHasPrimeImage],
        [RelType.MagazineHasIssue, RelationshipType.MagazineHasIssue],
        [RelType.MagazineHasImage, RelationshipType.MagazineHasImage],
        [RelType.MagazineHasPrimeImage, RelationshipType.MagazineHasPrimeImage],
        [RelType.MagazineIssueBelongsToMagazine, RelationshipType.MagazineIssueBelongsToMagazine],
        [RelType.MagazineIssueFollowsIssue, RelationshipType.MagazineIssueFollowsIssue],
        [RelType.MagazineIssueFollowedByIssue, RelationshipType.MagazineIssueFollowedByIssue],
        [RelType.MagazineIssueCoversCarModel, RelationshipType.MagazineIssueCoversCarModel],
        [RelType.MagazineIssuePresentsCarModelVariant, RelationshipType.MagazineIssuePresentsCarModelVariant],
        [RelType.MagazineIssueReviewedCarModelVariantWithRating, RelationshipType.MagazineIssueReviewedCarModelVariantWithRating],
        [RelType.MagazineIssueCoversRacingEvent, RelationshipType.MagazineIssueCoversRacingEvent],
        [RelType.MagazineIssueHasImage, RelationshipType.MagazineIssueHasImage],
        [RelType.MagazineIssueHasPrimeImage, RelationshipType.MagazineIssueHasPrimeImage],
        [RelType.RatingByMagazineIssue, RelationshipType.RatingByMagazineIssue],
        [RelType.RatingForCarModelVariant, RelationshipType.RatingForCarModelVariant],
        [RelType.RatingHasImage, RelationshipType.RatingHasImage],
        [RelType.RatingHasPrimeImage, RelationshipType.RatingHasPrimeImage],
        [RelType.ProgrammeHasEpisode, RelationshipType.ProgrammeHasEpisode],
        [RelType.ProgrammeHasImage, RelationshipType.ProgrammeHasImage],
        [RelType.ProgrammeHasPrimeImage, RelationshipType.ProgrammeHasPrimeImage],
        [RelType.ProgrammeEpisodeBelongsToProgramme, RelationshipType.ProgrammeEpisodeBelongsToProgramme],
        [RelType.ProgrammeEpisodeFollowsEpisode, RelationshipType.ProgrammeEpisodeFollowsEpisode],
        [RelType.ProgrammeEpisodeIsFollowedByEpisode, RelationshipType.ProgrammeEpisodeIsFollowedByEpisode],
        [RelType.ProgrammeEpisodeCoversCarModel, RelationshipType.ProgrammeEpisodeCoversCarModel],
        [RelType.ProgrammeEpisodeFeaturesCarModelVariant, RelationshipType.ProgrammeEpisodeFeaturesCarModelVariant],
        [RelType.ProgrammeEpisodeHasImage, RelationshipType.ProgrammeEpisodeHasImage],
        [RelType.ProgrammeEpisodeHasPrimeImage, RelationshipType.ProgrammeEpisodeHasPrimeImage],
        [RelType.MotorShowPresentsCarModelVariant, RelationshipType.MotorShowPresentsCarModelVariant],
        [RelType.MotorShowHasImage, RelationshipType.MotorShowHasImage],
        [RelType.MotorShowHasPrimeImage, RelationshipType.MotorShowHasPrimeImage],
        [RelType.VideoBelongsToNode, RelationshipType.VideoBelongsToNode],
        [RelType.VideoIsMainVideoOfNode, RelationshipType.VideoIsMainVideoOfNode],
        [RelType.ImageBelongsToNode, RelationshipType.ImageBelongsToNode],
        [RelType.ImageIsPrimeImageOfNode, RelationshipType.ImageIsPrimeImageOfNode],
    ])

    const relationshipType = mapping.get(relType)

    if (!relationshipType) {
        throw new RelationshipTypeMappingNotFoundError(relType)
    }

    return relationshipType
}
