export enum NodeType {
    Company = "Company",
    Brand = "Brand",
    CarModel = "Car Model",
    CarModelVariant = "Car Model Variant",
    RaceTrack = "Race Track",
    TrackLayout = "Track Layout",
    RacingSeries = "Racing Series",
    RacingEvent = "Racing Event",
    RacingSession = "Racing Session",
    SessionResult = "Session Result",
    LapTime = "Lap Time",
    RacingGame = "Racing Game",
    GamingPlatform = "Gaming Platform",
    Magazine = "Magazine",
    Image = "Image",
    Node = "",
}
