export type ValidationRule =
    'mandatory' |
    'imageProvider' |
    'videoProvider' |
    'airInduction' |
    'bodyStyle' |
    'capacityUnit' |
    'consumptionUnit' |
    'displacementUnit' |
    'drivetrain' |
    'energySource' |
    'engineConfiguration' |
    'engineType' |
    'powerUnit' |
    'speedUnit' |
    'torqueUnit' |
    'transmission' |
    'weightUnit' |
    'countryCode' |
    'currencyCode' |
    'issn' |
    'duration' |
    'date' |
    'magazineFocus' |
    'publicationFormat' |
    'publicationFrequency' |
    'modelScale' |
    'targetAudience' |
    'motorShowFocus' |
    'trackType' |
    'vehicleType' |
    'distanceUnit' |
    'scaleDirection' |
    'sessionResultStatus' |
    'lengthUnit' |
    'trackDirection' |
    'trackSurface' |
    'geoPosition' |
    'dateTime' |
    'string' |
    'number'
