on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-image:
    name: "Build docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{ inputs.version }}

      - name: Build
        run: docker build -t mc-api -f deployment/Dockerfile .

      - name: Tag image (concrete version)
        run: docker tag mc-api ghcr.io/${{ github.repository }}:${{ inputs.version }}

      - name: Tag image (latest)
        run: docker tag mc-api ghcr.io/${{ github.repository }}:latest

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image (concrete version)
        run: docker push ghcr.io/${{ github.repository }}:${{ inputs.version }}

      - name: Push image (latest)
        run: docker push ghcr.io/${{ github.repository }}:latest
