on:
  workflow_call:

jobs:
  build-image:
    name: "Build docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{ inputs.version }}

      - name: Build
        run: docker build -t mc-api:${{ inputs.version }} -f deployment/Dockerfile .
