name: Build docker image (manual trigger)

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (e.g. 0.13.0)
        required: true
        type: string

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image-and-push-to-ghcr.yml
    with:
      reference: refs/tags/${{ inputs.version }}
      version: ${{ inputs.version }}

  copy-image-to-docker-hub:
    uses: ./.github/workflows/copy-docker-image-from-ghcr-to-docker-hub.yml
    with:
      version: ${{ inputs.version }}
    needs: build-docker-image
    secrets: inherit
