name: Build docker image (triggered by new tag)

on:
  push:
    tags:
      - '*'

env:
  VERSION_NUMBER: ${ inputs.version:1 }

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image-and-push-to-ghcr.yml
    with:
      version: $VERSION_NUMBER

  copy-image-to-docker-hub:
    uses: ./.github/workflows/copy-docker-image-from-ghcr-to-docker-hub.yml
    with:
      version: $VERSION_NUMBER
    needs: build-docker-image
    secrets: inherit
