name: Build docker image (triggered by new tag)

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image-and-push-to-ghcr.yml
    with:
      version: ${ github.ref_name:1 }

  copy-image-to-docker-hub:
    uses: ./.github/workflows/copy-docker-image-from-ghcr-to-docker-hub.yml
    with:
      version: ${ github.ref_name:1 }
    needs: build-docker-image
    secrets: inherit
