name: Build Docker Image

on:
  workflow_call:
    inputs:
      reference:
        type: string
        default: ${{ github.ref }}
      package-name:
        type: string
        default: rest-api
      version:
        type: string
        default: ${{ github.sha }}

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.reference }}

      - name: Build
        run: docker build -t mc-api -f deployment/Dockerfile .

      - name: Tag image (concrete version)
        run: docker tag mc-api ghcr.io/more-cars/${{ inputs.package-name }}:${{ inputs.version }}

      - name: Tag image (latest)
        run: docker tag mc-api ghcr.io/more-cars/${{ inputs.package-name }}:latest

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR (concrete version)
        run: docker push ghcr.io/more-cars/${{ inputs.package-name }}:${{ inputs.version }}

      - name: Push image to GHCR (latest)
        run: docker push ghcr.io/more-cars/${{ inputs.package-name }}:latest
