name: Commit Stage

on:
  workflow_call:

jobs:
  api-schema-validation:
    uses: ./.github/workflows/validate-api-schema.yml

  lint-typescript-code:
    uses: ./.github/workflows/run-code-linter.yml

  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
