name: Deploy App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      package-name:
        type: string
        default: rest-api
      version:
        required: true
        type: string

jobs:
  deploy-app:
    name: Deploy App
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Authorizing GitHub to access the Google Cloud account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: http://${{ inputs.environment }}.api.fast-cars.info
          environment: ${{ inputs.environment }}

      - name: Performing the deployment in GKE
        run: npm run app:deploy
        env:
          TARGET_CLUSTER: gke
          TARGET_ENVIRONMENT: ${{ inputs.environment }}
          PACKAGE_NAME: ${{ inputs.package-name }}
          PACKAGE_VERSION: ${{ inputs.version }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: http://${{ inputs.environment }}.api.fast-cars.info
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: http://${{ inputs.environment }}.api.fast-cars.info
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
