on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy-app:
    name: 'Deploying app'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checking out the codebase'
        uses: actions/checkout@v4
      - name: 'Authorizing GitHub to access the Google Cloud account'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: 'Executing the deployment'
        run: npm run gke:deploy:testing
