on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-app:
    name: 'Deploying app'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checking out the codebase'
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: npm ci
      - name: 'Authorizing GitHub to access the Google Cloud account'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: debugging
        run: kubectl config get-contexts
      - name: 'Executing the deployment'
        run: npm run app:deploy
        env:
          TARGET_CLUSTER: gke
          TARGET_ENVIRONMENT: ${{ inputs.environment }}
          TARGET_VERSION: latest
