on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy-app:
    name: "Deploying app"
    runs-on: ubuntu-latest

    steps:
      - name: "Authorizing GitHub to access the Google Cloud account"
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'
      - name: 'Deploy'
        run: npm run gke:deploy:testing
