on:
  workflow_call:

jobs:
  push-image:
    name: "Push docker image to GitHub registry"
    runs-on: ubuntu-latest

    steps:
      - name: Tag image
        run: docker tag docker.io/library/mc-api:${{ inputs.version }} ghcr.io/${{ github.repository }}:${{ inputs.version }}

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:${{ inputs.version }}
