on:
  workflow_call:

jobs:
  run-unit-tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run tests:unit:coverage
      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/test-reports/unit/report.xml'
