name: Run All Test Suites

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  api-schema-validation:
    uses: ./.github/workflows/validate-api-schema.yml

  lint-typescript-code:
    uses: ./.github/workflows/lint-typescript-code.yml

  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
